
// Copyright 2020 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../chrome/browser/ui/cookie_controls/cookie_controls_controller.h

package org.chromium.chrome.browser.settings.website;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    CookieControlsControllerStatus.UNINITIALIZED, CookieControlsControllerStatus.ENABLED,
    CookieControlsControllerStatus.DISABLED, CookieControlsControllerStatus.DISABLED_FOR_SITE
})
@Retention(RetentionPolicy.SOURCE)
public @interface CookieControlsControllerStatus {
  int UNINITIALIZED = 0;
  /**
   * Third-Party cookie blocking is enabled.
   */
  int ENABLED = 1;
  /**
   * Third-Party cookie blocking is disabled.
   */
  int DISABLED = 2;
  /**
   * Third-Party cookie blocking is enabled in general but was disabled for this site.
   */
  int DISABLED_FOR_SITE = 3;
}
