// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_list_specifics.proto

package org.chromium.components.sync.protocol;

public final class AppListSpecificsOuterClass {
  private AppListSpecificsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
