// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_notification_specifics.proto

package org.chromium.components.sync.protocol;

/**
 * <pre>
 * An App Notification, to be delivered from Chrome Apps to the
 * Chrome browser through the Notification API.
 * </pre>
 *
 * Protobuf type {@code sync_pb.AppNotification}
 */
public  final class AppNotification extends
    com.google.protobuf.GeneratedMessageLite<
        AppNotification, AppNotification.Builder> implements
    // @@protoc_insertion_point(message_implements:sync_pb.AppNotification)
    AppNotificationOrBuilder {
  private AppNotification() {
    guid_ = "";
    appId_ = "";
    title_ = "";
    bodyText_ = "";
    linkUrl_ = "";
    linkText_ = "";
  }
  private int bitField0_;
  public static final int GUID_FIELD_NUMBER = 1;
  private java.lang.String guid_;
  /**
   * <pre>
   * Globally unique id. This is more robust for uniquely identifying each
   * notification and hence gives us flexibility in the future. In absence
   * of this, unique id would be (app_id, creation_timestamp_ms). But that
   * relies on creation_timestamp_ms being high resolution and is not
   * globally unique - only unique for a given user.
   * </pre>
   *
   * <code>optional string guid = 1;</code>
   */
  public boolean hasGuid() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * Globally unique id. This is more robust for uniquely identifying each
   * notification and hence gives us flexibility in the future. In absence
   * of this, unique id would be (app_id, creation_timestamp_ms). But that
   * relies on creation_timestamp_ms being high resolution and is not
   * globally unique - only unique for a given user.
   * </pre>
   *
   * <code>optional string guid = 1;</code>
   */
  public java.lang.String getGuid() {
    return guid_;
  }
  /**
   * <pre>
   * Globally unique id. This is more robust for uniquely identifying each
   * notification and hence gives us flexibility in the future. In absence
   * of this, unique id would be (app_id, creation_timestamp_ms). But that
   * relies on creation_timestamp_ms being high resolution and is not
   * globally unique - only unique for a given user.
   * </pre>
   *
   * <code>optional string guid = 1;</code>
   */
  public com.google.protobuf.ByteString
      getGuidBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(guid_);
  }
  /**
   * <pre>
   * Globally unique id. This is more robust for uniquely identifying each
   * notification and hence gives us flexibility in the future. In absence
   * of this, unique id would be (app_id, creation_timestamp_ms). But that
   * relies on creation_timestamp_ms being high resolution and is not
   * globally unique - only unique for a given user.
   * </pre>
   *
   * <code>optional string guid = 1;</code>
   */
  private void setGuid(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    guid_ = value;
  }
  /**
   * <pre>
   * Globally unique id. This is more robust for uniquely identifying each
   * notification and hence gives us flexibility in the future. In absence
   * of this, unique id would be (app_id, creation_timestamp_ms). But that
   * relies on creation_timestamp_ms being high resolution and is not
   * globally unique - only unique for a given user.
   * </pre>
   *
   * <code>optional string guid = 1;</code>
   */
  private void clearGuid() {
    bitField0_ = (bitField0_ & ~0x00000001);
    guid_ = getDefaultInstance().getGuid();
  }
  /**
   * <pre>
   * Globally unique id. This is more robust for uniquely identifying each
   * notification and hence gives us flexibility in the future. In absence
   * of this, unique id would be (app_id, creation_timestamp_ms). But that
   * relies on creation_timestamp_ms being high resolution and is not
   * globally unique - only unique for a given user.
   * </pre>
   *
   * <code>optional string guid = 1;</code>
   */
  private void setGuidBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    guid_ = value.toStringUtf8();
  }

  public static final int APP_ID_FIELD_NUMBER = 2;
  private java.lang.String appId_;
  /**
   * <pre>
   * Metadata, not shown directly to the user.
   * The unique App Id, as created by the webstore and used to
   * delegate messages to the applications. This is defined as 32 characters
   * </pre>
   *
   * <code>optional string app_id = 2;</code>
   */
  public boolean hasAppId() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <pre>
   * Metadata, not shown directly to the user.
   * The unique App Id, as created by the webstore and used to
   * delegate messages to the applications. This is defined as 32 characters
   * </pre>
   *
   * <code>optional string app_id = 2;</code>
   */
  public java.lang.String getAppId() {
    return appId_;
  }
  /**
   * <pre>
   * Metadata, not shown directly to the user.
   * The unique App Id, as created by the webstore and used to
   * delegate messages to the applications. This is defined as 32 characters
   * </pre>
   *
   * <code>optional string app_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAppIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(appId_);
  }
  /**
   * <pre>
   * Metadata, not shown directly to the user.
   * The unique App Id, as created by the webstore and used to
   * delegate messages to the applications. This is defined as 32 characters
   * </pre>
   *
   * <code>optional string app_id = 2;</code>
   */
  private void setAppId(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    appId_ = value;
  }
  /**
   * <pre>
   * Metadata, not shown directly to the user.
   * The unique App Id, as created by the webstore and used to
   * delegate messages to the applications. This is defined as 32 characters
   * </pre>
   *
   * <code>optional string app_id = 2;</code>
   */
  private void clearAppId() {
    bitField0_ = (bitField0_ & ~0x00000002);
    appId_ = getDefaultInstance().getAppId();
  }
  /**
   * <pre>
   * Metadata, not shown directly to the user.
   * The unique App Id, as created by the webstore and used to
   * delegate messages to the applications. This is defined as 32 characters
   * </pre>
   *
   * <code>optional string app_id = 2;</code>
   */
  private void setAppIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    appId_ = value.toStringUtf8();
  }

  public static final int CREATION_TIMESTAMP_MS_FIELD_NUMBER = 3;
  private long creationTimestampMs_;
  /**
   * <pre>
   * Timestamp when the message was created in milliseconds.
   * This is seperate from ctime as this is only set by the application.
   * </pre>
   *
   * <code>optional int64 creation_timestamp_ms = 3;</code>
   */
  public boolean hasCreationTimestampMs() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <pre>
   * Timestamp when the message was created in milliseconds.
   * This is seperate from ctime as this is only set by the application.
   * </pre>
   *
   * <code>optional int64 creation_timestamp_ms = 3;</code>
   */
  public long getCreationTimestampMs() {
    return creationTimestampMs_;
  }
  /**
   * <pre>
   * Timestamp when the message was created in milliseconds.
   * This is seperate from ctime as this is only set by the application.
   * </pre>
   *
   * <code>optional int64 creation_timestamp_ms = 3;</code>
   */
  private void setCreationTimestampMs(long value) {
    bitField0_ |= 0x00000004;
    creationTimestampMs_ = value;
  }
  /**
   * <pre>
   * Timestamp when the message was created in milliseconds.
   * This is seperate from ctime as this is only set by the application.
   * </pre>
   *
   * <code>optional int64 creation_timestamp_ms = 3;</code>
   */
  private void clearCreationTimestampMs() {
    bitField0_ = (bitField0_ & ~0x00000004);
    creationTimestampMs_ = 0L;
  }

  public static final int TITLE_FIELD_NUMBER = 4;
  private java.lang.String title_;
  /**
   * <pre>
   * Payload - these fields are visible to the user content is defined by the
   * app. The fields are described in:
   * chrome/browser/extensions/app_notification.h
   * </pre>
   *
   * <code>optional string title = 4;</code>
   */
  public boolean hasTitle() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <pre>
   * Payload - these fields are visible to the user content is defined by the
   * app. The fields are described in:
   * chrome/browser/extensions/app_notification.h
   * </pre>
   *
   * <code>optional string title = 4;</code>
   */
  public java.lang.String getTitle() {
    return title_;
  }
  /**
   * <pre>
   * Payload - these fields are visible to the user content is defined by the
   * app. The fields are described in:
   * chrome/browser/extensions/app_notification.h
   * </pre>
   *
   * <code>optional string title = 4;</code>
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(title_);
  }
  /**
   * <pre>
   * Payload - these fields are visible to the user content is defined by the
   * app. The fields are described in:
   * chrome/browser/extensions/app_notification.h
   * </pre>
   *
   * <code>optional string title = 4;</code>
   */
  private void setTitle(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
    title_ = value;
  }
  /**
   * <pre>
   * Payload - these fields are visible to the user content is defined by the
   * app. The fields are described in:
   * chrome/browser/extensions/app_notification.h
   * </pre>
   *
   * <code>optional string title = 4;</code>
   */
  private void clearTitle() {
    bitField0_ = (bitField0_ & ~0x00000008);
    title_ = getDefaultInstance().getTitle();
  }
  /**
   * <pre>
   * Payload - these fields are visible to the user content is defined by the
   * app. The fields are described in:
   * chrome/browser/extensions/app_notification.h
   * </pre>
   *
   * <code>optional string title = 4;</code>
   */
  private void setTitleBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
    title_ = value.toStringUtf8();
  }

  public static final int BODY_TEXT_FIELD_NUMBER = 5;
  private java.lang.String bodyText_;
  /**
   * <code>optional string body_text = 5;</code>
   */
  public boolean hasBodyText() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional string body_text = 5;</code>
   */
  public java.lang.String getBodyText() {
    return bodyText_;
  }
  /**
   * <code>optional string body_text = 5;</code>
   */
  public com.google.protobuf.ByteString
      getBodyTextBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(bodyText_);
  }
  /**
   * <code>optional string body_text = 5;</code>
   */
  private void setBodyText(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
    bodyText_ = value;
  }
  /**
   * <code>optional string body_text = 5;</code>
   */
  private void clearBodyText() {
    bitField0_ = (bitField0_ & ~0x00000010);
    bodyText_ = getDefaultInstance().getBodyText();
  }
  /**
   * <code>optional string body_text = 5;</code>
   */
  private void setBodyTextBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
    bodyText_ = value.toStringUtf8();
  }

  public static final int LINK_URL_FIELD_NUMBER = 6;
  private java.lang.String linkUrl_;
  /**
   * <code>optional string link_url = 6;</code>
   */
  public boolean hasLinkUrl() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional string link_url = 6;</code>
   */
  public java.lang.String getLinkUrl() {
    return linkUrl_;
  }
  /**
   * <code>optional string link_url = 6;</code>
   */
  public com.google.protobuf.ByteString
      getLinkUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(linkUrl_);
  }
  /**
   * <code>optional string link_url = 6;</code>
   */
  private void setLinkUrl(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
    linkUrl_ = value;
  }
  /**
   * <code>optional string link_url = 6;</code>
   */
  private void clearLinkUrl() {
    bitField0_ = (bitField0_ & ~0x00000020);
    linkUrl_ = getDefaultInstance().getLinkUrl();
  }
  /**
   * <code>optional string link_url = 6;</code>
   */
  private void setLinkUrlBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
    linkUrl_ = value.toStringUtf8();
  }

  public static final int LINK_TEXT_FIELD_NUMBER = 7;
  private java.lang.String linkText_;
  /**
   * <code>optional string link_text = 7;</code>
   */
  public boolean hasLinkText() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional string link_text = 7;</code>
   */
  public java.lang.String getLinkText() {
    return linkText_;
  }
  /**
   * <code>optional string link_text = 7;</code>
   */
  public com.google.protobuf.ByteString
      getLinkTextBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(linkText_);
  }
  /**
   * <code>optional string link_text = 7;</code>
   */
  private void setLinkText(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
    linkText_ = value;
  }
  /**
   * <code>optional string link_text = 7;</code>
   */
  private void clearLinkText() {
    bitField0_ = (bitField0_ & ~0x00000040);
    linkText_ = getDefaultInstance().getLinkText();
  }
  /**
   * <code>optional string link_text = 7;</code>
   */
  private void setLinkTextBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
    linkText_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeString(1, getGuid());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeString(2, getAppId());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt64(3, creationTimestampMs_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeString(4, getTitle());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeString(5, getBodyText());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeString(6, getLinkUrl());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeString(7, getLinkText());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getGuid());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getAppId());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, creationTimestampMs_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(4, getTitle());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(5, getBodyText());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(6, getLinkUrl());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(7, getLinkText());
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static org.chromium.components.sync.protocol.AppNotification parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.AppNotification parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.AppNotification parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.AppNotification parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.AppNotification parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.AppNotification parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.AppNotification parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.AppNotification parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.AppNotification parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.AppNotification parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.chromium.components.sync.protocol.AppNotification prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * An App Notification, to be delivered from Chrome Apps to the
   * Chrome browser through the Notification API.
   * </pre>
   *
   * Protobuf type {@code sync_pb.AppNotification}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.components.sync.protocol.AppNotification, Builder> implements
      // @@protoc_insertion_point(builder_implements:sync_pb.AppNotification)
      org.chromium.components.sync.protocol.AppNotificationOrBuilder {
    // Construct using org.chromium.components.sync.protocol.AppNotification.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Globally unique id. This is more robust for uniquely identifying each
     * notification and hence gives us flexibility in the future. In absence
     * of this, unique id would be (app_id, creation_timestamp_ms). But that
     * relies on creation_timestamp_ms being high resolution and is not
     * globally unique - only unique for a given user.
     * </pre>
     *
     * <code>optional string guid = 1;</code>
     */
    public boolean hasGuid() {
      return instance.hasGuid();
    }
    /**
     * <pre>
     * Globally unique id. This is more robust for uniquely identifying each
     * notification and hence gives us flexibility in the future. In absence
     * of this, unique id would be (app_id, creation_timestamp_ms). But that
     * relies on creation_timestamp_ms being high resolution and is not
     * globally unique - only unique for a given user.
     * </pre>
     *
     * <code>optional string guid = 1;</code>
     */
    public java.lang.String getGuid() {
      return instance.getGuid();
    }
    /**
     * <pre>
     * Globally unique id. This is more robust for uniquely identifying each
     * notification and hence gives us flexibility in the future. In absence
     * of this, unique id would be (app_id, creation_timestamp_ms). But that
     * relies on creation_timestamp_ms being high resolution and is not
     * globally unique - only unique for a given user.
     * </pre>
     *
     * <code>optional string guid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGuidBytes() {
      return instance.getGuidBytes();
    }
    /**
     * <pre>
     * Globally unique id. This is more robust for uniquely identifying each
     * notification and hence gives us flexibility in the future. In absence
     * of this, unique id would be (app_id, creation_timestamp_ms). But that
     * relies on creation_timestamp_ms being high resolution and is not
     * globally unique - only unique for a given user.
     * </pre>
     *
     * <code>optional string guid = 1;</code>
     */
    public Builder setGuid(
        java.lang.String value) {
      copyOnWrite();
      instance.setGuid(value);
      return this;
    }
    /**
     * <pre>
     * Globally unique id. This is more robust for uniquely identifying each
     * notification and hence gives us flexibility in the future. In absence
     * of this, unique id would be (app_id, creation_timestamp_ms). But that
     * relies on creation_timestamp_ms being high resolution and is not
     * globally unique - only unique for a given user.
     * </pre>
     *
     * <code>optional string guid = 1;</code>
     */
    public Builder clearGuid() {
      copyOnWrite();
      instance.clearGuid();
      return this;
    }
    /**
     * <pre>
     * Globally unique id. This is more robust for uniquely identifying each
     * notification and hence gives us flexibility in the future. In absence
     * of this, unique id would be (app_id, creation_timestamp_ms). But that
     * relies on creation_timestamp_ms being high resolution and is not
     * globally unique - only unique for a given user.
     * </pre>
     *
     * <code>optional string guid = 1;</code>
     */
    public Builder setGuidBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setGuidBytes(value);
      return this;
    }

    /**
     * <pre>
     * Metadata, not shown directly to the user.
     * The unique App Id, as created by the webstore and used to
     * delegate messages to the applications. This is defined as 32 characters
     * </pre>
     *
     * <code>optional string app_id = 2;</code>
     */
    public boolean hasAppId() {
      return instance.hasAppId();
    }
    /**
     * <pre>
     * Metadata, not shown directly to the user.
     * The unique App Id, as created by the webstore and used to
     * delegate messages to the applications. This is defined as 32 characters
     * </pre>
     *
     * <code>optional string app_id = 2;</code>
     */
    public java.lang.String getAppId() {
      return instance.getAppId();
    }
    /**
     * <pre>
     * Metadata, not shown directly to the user.
     * The unique App Id, as created by the webstore and used to
     * delegate messages to the applications. This is defined as 32 characters
     * </pre>
     *
     * <code>optional string app_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      return instance.getAppIdBytes();
    }
    /**
     * <pre>
     * Metadata, not shown directly to the user.
     * The unique App Id, as created by the webstore and used to
     * delegate messages to the applications. This is defined as 32 characters
     * </pre>
     *
     * <code>optional string app_id = 2;</code>
     */
    public Builder setAppId(
        java.lang.String value) {
      copyOnWrite();
      instance.setAppId(value);
      return this;
    }
    /**
     * <pre>
     * Metadata, not shown directly to the user.
     * The unique App Id, as created by the webstore and used to
     * delegate messages to the applications. This is defined as 32 characters
     * </pre>
     *
     * <code>optional string app_id = 2;</code>
     */
    public Builder clearAppId() {
      copyOnWrite();
      instance.clearAppId();
      return this;
    }
    /**
     * <pre>
     * Metadata, not shown directly to the user.
     * The unique App Id, as created by the webstore and used to
     * delegate messages to the applications. This is defined as 32 characters
     * </pre>
     *
     * <code>optional string app_id = 2;</code>
     */
    public Builder setAppIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAppIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * Timestamp when the message was created in milliseconds.
     * This is seperate from ctime as this is only set by the application.
     * </pre>
     *
     * <code>optional int64 creation_timestamp_ms = 3;</code>
     */
    public boolean hasCreationTimestampMs() {
      return instance.hasCreationTimestampMs();
    }
    /**
     * <pre>
     * Timestamp when the message was created in milliseconds.
     * This is seperate from ctime as this is only set by the application.
     * </pre>
     *
     * <code>optional int64 creation_timestamp_ms = 3;</code>
     */
    public long getCreationTimestampMs() {
      return instance.getCreationTimestampMs();
    }
    /**
     * <pre>
     * Timestamp when the message was created in milliseconds.
     * This is seperate from ctime as this is only set by the application.
     * </pre>
     *
     * <code>optional int64 creation_timestamp_ms = 3;</code>
     */
    public Builder setCreationTimestampMs(long value) {
      copyOnWrite();
      instance.setCreationTimestampMs(value);
      return this;
    }
    /**
     * <pre>
     * Timestamp when the message was created in milliseconds.
     * This is seperate from ctime as this is only set by the application.
     * </pre>
     *
     * <code>optional int64 creation_timestamp_ms = 3;</code>
     */
    public Builder clearCreationTimestampMs() {
      copyOnWrite();
      instance.clearCreationTimestampMs();
      return this;
    }

    /**
     * <pre>
     * Payload - these fields are visible to the user content is defined by the
     * app. The fields are described in:
     * chrome/browser/extensions/app_notification.h
     * </pre>
     *
     * <code>optional string title = 4;</code>
     */
    public boolean hasTitle() {
      return instance.hasTitle();
    }
    /**
     * <pre>
     * Payload - these fields are visible to the user content is defined by the
     * app. The fields are described in:
     * chrome/browser/extensions/app_notification.h
     * </pre>
     *
     * <code>optional string title = 4;</code>
     */
    public java.lang.String getTitle() {
      return instance.getTitle();
    }
    /**
     * <pre>
     * Payload - these fields are visible to the user content is defined by the
     * app. The fields are described in:
     * chrome/browser/extensions/app_notification.h
     * </pre>
     *
     * <code>optional string title = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return instance.getTitleBytes();
    }
    /**
     * <pre>
     * Payload - these fields are visible to the user content is defined by the
     * app. The fields are described in:
     * chrome/browser/extensions/app_notification.h
     * </pre>
     *
     * <code>optional string title = 4;</code>
     */
    public Builder setTitle(
        java.lang.String value) {
      copyOnWrite();
      instance.setTitle(value);
      return this;
    }
    /**
     * <pre>
     * Payload - these fields are visible to the user content is defined by the
     * app. The fields are described in:
     * chrome/browser/extensions/app_notification.h
     * </pre>
     *
     * <code>optional string title = 4;</code>
     */
    public Builder clearTitle() {
      copyOnWrite();
      instance.clearTitle();
      return this;
    }
    /**
     * <pre>
     * Payload - these fields are visible to the user content is defined by the
     * app. The fields are described in:
     * chrome/browser/extensions/app_notification.h
     * </pre>
     *
     * <code>optional string title = 4;</code>
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTitleBytes(value);
      return this;
    }

    /**
     * <code>optional string body_text = 5;</code>
     */
    public boolean hasBodyText() {
      return instance.hasBodyText();
    }
    /**
     * <code>optional string body_text = 5;</code>
     */
    public java.lang.String getBodyText() {
      return instance.getBodyText();
    }
    /**
     * <code>optional string body_text = 5;</code>
     */
    public com.google.protobuf.ByteString
        getBodyTextBytes() {
      return instance.getBodyTextBytes();
    }
    /**
     * <code>optional string body_text = 5;</code>
     */
    public Builder setBodyText(
        java.lang.String value) {
      copyOnWrite();
      instance.setBodyText(value);
      return this;
    }
    /**
     * <code>optional string body_text = 5;</code>
     */
    public Builder clearBodyText() {
      copyOnWrite();
      instance.clearBodyText();
      return this;
    }
    /**
     * <code>optional string body_text = 5;</code>
     */
    public Builder setBodyTextBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBodyTextBytes(value);
      return this;
    }

    /**
     * <code>optional string link_url = 6;</code>
     */
    public boolean hasLinkUrl() {
      return instance.hasLinkUrl();
    }
    /**
     * <code>optional string link_url = 6;</code>
     */
    public java.lang.String getLinkUrl() {
      return instance.getLinkUrl();
    }
    /**
     * <code>optional string link_url = 6;</code>
     */
    public com.google.protobuf.ByteString
        getLinkUrlBytes() {
      return instance.getLinkUrlBytes();
    }
    /**
     * <code>optional string link_url = 6;</code>
     */
    public Builder setLinkUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setLinkUrl(value);
      return this;
    }
    /**
     * <code>optional string link_url = 6;</code>
     */
    public Builder clearLinkUrl() {
      copyOnWrite();
      instance.clearLinkUrl();
      return this;
    }
    /**
     * <code>optional string link_url = 6;</code>
     */
    public Builder setLinkUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLinkUrlBytes(value);
      return this;
    }

    /**
     * <code>optional string link_text = 7;</code>
     */
    public boolean hasLinkText() {
      return instance.hasLinkText();
    }
    /**
     * <code>optional string link_text = 7;</code>
     */
    public java.lang.String getLinkText() {
      return instance.getLinkText();
    }
    /**
     * <code>optional string link_text = 7;</code>
     */
    public com.google.protobuf.ByteString
        getLinkTextBytes() {
      return instance.getLinkTextBytes();
    }
    /**
     * <code>optional string link_text = 7;</code>
     */
    public Builder setLinkText(
        java.lang.String value) {
      copyOnWrite();
      instance.setLinkText(value);
      return this;
    }
    /**
     * <code>optional string link_text = 7;</code>
     */
    public Builder clearLinkText() {
      copyOnWrite();
      instance.clearLinkText();
      return this;
    }
    /**
     * <code>optional string link_text = 7;</code>
     */
    public Builder setLinkTextBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLinkTextBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sync_pb.AppNotification)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.components.sync.protocol.AppNotification();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        org.chromium.components.sync.protocol.AppNotification other = (org.chromium.components.sync.protocol.AppNotification) arg1;
        guid_ = visitor.visitString(
            hasGuid(), guid_,
            other.hasGuid(), other.guid_);
        appId_ = visitor.visitString(
            hasAppId(), appId_,
            other.hasAppId(), other.appId_);
        creationTimestampMs_ = visitor.visitLong(
            hasCreationTimestampMs(), creationTimestampMs_,
            other.hasCreationTimestampMs(), other.creationTimestampMs_);
        title_ = visitor.visitString(
            hasTitle(), title_,
            other.hasTitle(), other.title_);
        bodyText_ = visitor.visitString(
            hasBodyText(), bodyText_,
            other.hasBodyText(), other.bodyText_);
        linkUrl_ = visitor.visitString(
            hasLinkUrl(), linkUrl_,
            other.hasLinkUrl(), other.linkUrl_);
        linkText_ = visitor.visitString(
            hasLinkText(), linkText_,
            other.hasLinkText(), other.linkText_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readString();
                bitField0_ |= 0x00000001;
                guid_ = s;
                break;
              }
              case 18: {
                String s = input.readString();
                bitField0_ |= 0x00000002;
                appId_ = s;
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                creationTimestampMs_ = input.readInt64();
                break;
              }
              case 34: {
                String s = input.readString();
                bitField0_ |= 0x00000008;
                title_ = s;
                break;
              }
              case 42: {
                String s = input.readString();
                bitField0_ |= 0x00000010;
                bodyText_ = s;
                break;
              }
              case 50: {
                String s = input.readString();
                bitField0_ |= 0x00000020;
                linkUrl_ = s;
                break;
              }
              case 58: {
                String s = input.readString();
                bitField0_ |= 0x00000040;
                linkText_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (org.chromium.components.sync.protocol.AppNotification.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sync_pb.AppNotification)
  private static final org.chromium.components.sync.protocol.AppNotification DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AppNotification();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static org.chromium.components.sync.protocol.AppNotification getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AppNotification> PARSER;

  public static com.google.protobuf.Parser<AppNotification> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

