// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: autofill_specifics.proto

package org.chromium.components.sync.protocol;

public interface AutofillProfileSpecificsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sync_pb.AutofillProfileSpecifics)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string guid = 15;</code>
   */
  boolean hasGuid();
  /**
   * <code>optional string guid = 15;</code>
   */
  java.lang.String getGuid();
  /**
   * <code>optional string guid = 15;</code>
   */
  com.google.protobuf.ByteString
      getGuidBytes();

  /**
   * <code>optional string origin = 16;</code>
   */
  boolean hasOrigin();
  /**
   * <code>optional string origin = 16;</code>
   */
  java.lang.String getOrigin();
  /**
   * <code>optional string origin = 16;</code>
   */
  com.google.protobuf.ByteString
      getOriginBytes();

  /**
   * <code>optional int64 use_count = 22;</code>
   */
  boolean hasUseCount();
  /**
   * <code>optional int64 use_count = 22;</code>
   */
  long getUseCount();

  /**
   * <pre>
   * The time_t value of the last time this profile was used. This
   * value makes sense wrt base::Time::To/FromTimeT, which measures
   * from the Windows epoch.
   * </pre>
   *
   * <code>optional int64 use_date = 23;</code>
   */
  boolean hasUseDate();
  /**
   * <pre>
   * The time_t value of the last time this profile was used. This
   * value makes sense wrt base::Time::To/FromTimeT, which measures
   * from the Windows epoch.
   * </pre>
   *
   * <code>optional int64 use_date = 23;</code>
   */
  long getUseDate();

  /**
   * <pre>
   * Contact info.
   * </pre>
   *
   * <code>repeated string name_first = 2;</code>
   */
  java.util.List<String>
      getNameFirstList();
  /**
   * <pre>
   * Contact info.
   * </pre>
   *
   * <code>repeated string name_first = 2;</code>
   */
  int getNameFirstCount();
  /**
   * <pre>
   * Contact info.
   * </pre>
   *
   * <code>repeated string name_first = 2;</code>
   */
  java.lang.String getNameFirst(int index);
  /**
   * <pre>
   * Contact info.
   * </pre>
   *
   * <code>repeated string name_first = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameFirstBytes(int index);

  /**
   * <code>repeated string name_middle = 3;</code>
   */
  java.util.List<String>
      getNameMiddleList();
  /**
   * <code>repeated string name_middle = 3;</code>
   */
  int getNameMiddleCount();
  /**
   * <code>repeated string name_middle = 3;</code>
   */
  java.lang.String getNameMiddle(int index);
  /**
   * <code>repeated string name_middle = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameMiddleBytes(int index);

  /**
   * <code>repeated string name_last = 4;</code>
   */
  java.util.List<String>
      getNameLastList();
  /**
   * <code>repeated string name_last = 4;</code>
   */
  int getNameLastCount();
  /**
   * <code>repeated string name_last = 4;</code>
   */
  java.lang.String getNameLast(int index);
  /**
   * <code>repeated string name_last = 4;</code>
   */
  com.google.protobuf.ByteString
      getNameLastBytes(int index);

  /**
   * <code>repeated string name_full = 21;</code>
   */
  java.util.List<String>
      getNameFullList();
  /**
   * <code>repeated string name_full = 21;</code>
   */
  int getNameFullCount();
  /**
   * <code>repeated string name_full = 21;</code>
   */
  java.lang.String getNameFull(int index);
  /**
   * <code>repeated string name_full = 21;</code>
   */
  com.google.protobuf.ByteString
      getNameFullBytes(int index);

  /**
   * <code>repeated string email_address = 5;</code>
   */
  java.util.List<String>
      getEmailAddressList();
  /**
   * <code>repeated string email_address = 5;</code>
   */
  int getEmailAddressCount();
  /**
   * <code>repeated string email_address = 5;</code>
   */
  java.lang.String getEmailAddress(int index);
  /**
   * <code>repeated string email_address = 5;</code>
   */
  com.google.protobuf.ByteString
      getEmailAddressBytes(int index);

  /**
   * <code>optional string company_name = 6;</code>
   */
  boolean hasCompanyName();
  /**
   * <code>optional string company_name = 6;</code>
   */
  java.lang.String getCompanyName();
  /**
   * <code>optional string company_name = 6;</code>
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <pre>
   * Address.
   * </pre>
   *
   * <code>optional string address_home_line1 = 7;</code>
   */
  boolean hasAddressHomeLine1();
  /**
   * <pre>
   * Address.
   * </pre>
   *
   * <code>optional string address_home_line1 = 7;</code>
   */
  java.lang.String getAddressHomeLine1();
  /**
   * <pre>
   * Address.
   * </pre>
   *
   * <code>optional string address_home_line1 = 7;</code>
   */
  com.google.protobuf.ByteString
      getAddressHomeLine1Bytes();

  /**
   * <code>optional string address_home_line2 = 8;</code>
   */
  boolean hasAddressHomeLine2();
  /**
   * <code>optional string address_home_line2 = 8;</code>
   */
  java.lang.String getAddressHomeLine2();
  /**
   * <code>optional string address_home_line2 = 8;</code>
   */
  com.google.protobuf.ByteString
      getAddressHomeLine2Bytes();

  /**
   * <code>optional string address_home_city = 9;</code>
   */
  boolean hasAddressHomeCity();
  /**
   * <code>optional string address_home_city = 9;</code>
   */
  java.lang.String getAddressHomeCity();
  /**
   * <code>optional string address_home_city = 9;</code>
   */
  com.google.protobuf.ByteString
      getAddressHomeCityBytes();

  /**
   * <code>optional string address_home_state = 10;</code>
   */
  boolean hasAddressHomeState();
  /**
   * <code>optional string address_home_state = 10;</code>
   */
  java.lang.String getAddressHomeState();
  /**
   * <code>optional string address_home_state = 10;</code>
   */
  com.google.protobuf.ByteString
      getAddressHomeStateBytes();

  /**
   * <code>optional string address_home_zip = 11;</code>
   */
  boolean hasAddressHomeZip();
  /**
   * <code>optional string address_home_zip = 11;</code>
   */
  java.lang.String getAddressHomeZip();
  /**
   * <code>optional string address_home_zip = 11;</code>
   */
  com.google.protobuf.ByteString
      getAddressHomeZipBytes();

  /**
   * <code>optional string address_home_country = 12;</code>
   */
  boolean hasAddressHomeCountry();
  /**
   * <code>optional string address_home_country = 12;</code>
   */
  java.lang.String getAddressHomeCountry();
  /**
   * <code>optional string address_home_country = 12;</code>
   */
  com.google.protobuf.ByteString
      getAddressHomeCountryBytes();

  /**
   * <pre>
   * Additional address fields for i18n.
   * </pre>
   *
   * <code>optional string address_home_street_address = 17;</code>
   */
  boolean hasAddressHomeStreetAddress();
  /**
   * <pre>
   * Additional address fields for i18n.
   * </pre>
   *
   * <code>optional string address_home_street_address = 17;</code>
   */
  java.lang.String getAddressHomeStreetAddress();
  /**
   * <pre>
   * Additional address fields for i18n.
   * </pre>
   *
   * <code>optional string address_home_street_address = 17;</code>
   */
  com.google.protobuf.ByteString
      getAddressHomeStreetAddressBytes();

  /**
   * <code>optional string address_home_sorting_code = 18;</code>
   */
  boolean hasAddressHomeSortingCode();
  /**
   * <code>optional string address_home_sorting_code = 18;</code>
   */
  java.lang.String getAddressHomeSortingCode();
  /**
   * <code>optional string address_home_sorting_code = 18;</code>
   */
  com.google.protobuf.ByteString
      getAddressHomeSortingCodeBytes();

  /**
   * <code>optional string address_home_dependent_locality = 19;</code>
   */
  boolean hasAddressHomeDependentLocality();
  /**
   * <code>optional string address_home_dependent_locality = 19;</code>
   */
  java.lang.String getAddressHomeDependentLocality();
  /**
   * <code>optional string address_home_dependent_locality = 19;</code>
   */
  com.google.protobuf.ByteString
      getAddressHomeDependentLocalityBytes();

  /**
   * <code>optional string address_home_language_code = 20;</code>
   */
  boolean hasAddressHomeLanguageCode();
  /**
   * <code>optional string address_home_language_code = 20;</code>
   */
  java.lang.String getAddressHomeLanguageCode();
  /**
   * <code>optional string address_home_language_code = 20;</code>
   */
  com.google.protobuf.ByteString
      getAddressHomeLanguageCodeBytes();

  /**
   * <pre>
   * Phone.
   * </pre>
   *
   * <code>repeated string phone_home_whole_number = 13;</code>
   */
  java.util.List<String>
      getPhoneHomeWholeNumberList();
  /**
   * <pre>
   * Phone.
   * </pre>
   *
   * <code>repeated string phone_home_whole_number = 13;</code>
   */
  int getPhoneHomeWholeNumberCount();
  /**
   * <pre>
   * Phone.
   * </pre>
   *
   * <code>repeated string phone_home_whole_number = 13;</code>
   */
  java.lang.String getPhoneHomeWholeNumber(int index);
  /**
   * <pre>
   * Phone.
   * </pre>
   *
   * <code>repeated string phone_home_whole_number = 13;</code>
   */
  com.google.protobuf.ByteString
      getPhoneHomeWholeNumberBytes(int index);

  /**
   * <pre>
   * Validity bitfield.
   * Each set of two bits represents the validity state of a specific part of
   * the Autofill address. For more info please refer to autofill_profile.h.
   * </pre>
   *
   * <code>optional int64 validity_state_bitfield = 24;</code>
   */
  boolean hasValidityStateBitfield();
  /**
   * <pre>
   * Validity bitfield.
   * Each set of two bits represents the validity state of a specific part of
   * the Autofill address. For more info please refer to autofill_profile.h.
   * </pre>
   *
   * <code>optional int64 validity_state_bitfield = 24;</code>
   */
  long getValidityStateBitfield();

  /**
   * <pre>
   * Denotes whether the validity_state_bitfield is updated according to the
   * changes in the autofill profile values.
   * </pre>
   *
   * <code>optional bool is_client_validity_states_updated = 25;</code>
   */
  boolean hasIsClientValidityStatesUpdated();
  /**
   * <pre>
   * Denotes whether the validity_state_bitfield is updated according to the
   * changes in the autofill profile values.
   * </pre>
   *
   * <code>optional bool is_client_validity_states_updated = 25;</code>
   */
  boolean getIsClientValidityStatesUpdated();

  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>optional string label = 1 [deprecated = true];</code>
   */
  @java.lang.Deprecated boolean hasLabel();
  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>optional string label = 1 [deprecated = true];</code>
   */
  @java.lang.Deprecated java.lang.String getLabel();
  /**
   * <pre>
   * Deprecated.
   * </pre>
   *
   * <code>optional string label = 1 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>optional string phone_fax_whole_number = 14 [deprecated = true];</code>
   */
  @java.lang.Deprecated boolean hasPhoneFaxWholeNumber();
  /**
   * <code>optional string phone_fax_whole_number = 14 [deprecated = true];</code>
   */
  @java.lang.Deprecated java.lang.String getPhoneFaxWholeNumber();
  /**
   * <code>optional string phone_fax_whole_number = 14 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.google.protobuf.ByteString
      getPhoneFaxWholeNumberBytes();
}
