// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: experiments_specifics.proto

package org.chromium.components.sync.protocol;

public interface EnhancedBookmarksFlagsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sync_pb.EnhancedBookmarksFlags)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional bool enabled = 1;</code>
   */
  boolean hasEnabled();
  /**
   * <code>optional bool enabled = 1;</code>
   */
  boolean getEnabled();

  /**
   * <code>optional string extension_id = 2;</code>
   */
  boolean hasExtensionId();
  /**
   * <code>optional string extension_id = 2;</code>
   */
  java.lang.String getExtensionId();
  /**
   * <code>optional string extension_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getExtensionIdBytes();
}
