// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: experiments_specifics.proto

package org.chromium.components.sync.protocol;

/**
 * <pre>
 * Contains one flag or set of related flags.  Each node of the experiments type
 * will have a unique_client_tag identifying which flags it contains.  By
 * convention, the tag name should match the sub-message name.
 * </pre>
 *
 * Protobuf type {@code sync_pb.ExperimentsSpecifics}
 */
public  final class ExperimentsSpecifics extends
    com.google.protobuf.GeneratedMessageLite<
        ExperimentsSpecifics, ExperimentsSpecifics.Builder> implements
    // @@protoc_insertion_point(message_implements:sync_pb.ExperimentsSpecifics)
    ExperimentsSpecificsOrBuilder {
  private ExperimentsSpecifics() {
  }
  private int bitField0_;
  public static final int KEYSTORE_ENCRYPTION_FIELD_NUMBER = 1;
  private org.chromium.components.sync.protocol.KeystoreEncryptionFlags keystoreEncryption_;
  /**
   * <code>optional .sync_pb.KeystoreEncryptionFlags keystore_encryption = 1;</code>
   */
  public boolean hasKeystoreEncryption() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional .sync_pb.KeystoreEncryptionFlags keystore_encryption = 1;</code>
   */
  public org.chromium.components.sync.protocol.KeystoreEncryptionFlags getKeystoreEncryption() {
    return keystoreEncryption_ == null ? org.chromium.components.sync.protocol.KeystoreEncryptionFlags.getDefaultInstance() : keystoreEncryption_;
  }
  /**
   * <code>optional .sync_pb.KeystoreEncryptionFlags keystore_encryption = 1;</code>
   */
  private void setKeystoreEncryption(org.chromium.components.sync.protocol.KeystoreEncryptionFlags value) {
    if (value == null) {
      throw new NullPointerException();
    }
    keystoreEncryption_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>optional .sync_pb.KeystoreEncryptionFlags keystore_encryption = 1;</code>
   */
  private void setKeystoreEncryption(
      org.chromium.components.sync.protocol.KeystoreEncryptionFlags.Builder builderForValue) {
    keystoreEncryption_ = builderForValue.build();
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .sync_pb.KeystoreEncryptionFlags keystore_encryption = 1;</code>
   */
  private void mergeKeystoreEncryption(org.chromium.components.sync.protocol.KeystoreEncryptionFlags value) {
    if (keystoreEncryption_ != null &&
        keystoreEncryption_ != org.chromium.components.sync.protocol.KeystoreEncryptionFlags.getDefaultInstance()) {
      keystoreEncryption_ =
        org.chromium.components.sync.protocol.KeystoreEncryptionFlags.newBuilder(keystoreEncryption_).mergeFrom(value).buildPartial();
    } else {
      keystoreEncryption_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>optional .sync_pb.KeystoreEncryptionFlags keystore_encryption = 1;</code>
   */
  private void clearKeystoreEncryption() {  keystoreEncryption_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int HISTORY_DELETE_DIRECTIVES_FIELD_NUMBER = 2;
  private org.chromium.components.sync.protocol.HistoryDeleteDirectives historyDeleteDirectives_;
  /**
   * <code>optional .sync_pb.HistoryDeleteDirectives history_delete_directives = 2;</code>
   */
  public boolean hasHistoryDeleteDirectives() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional .sync_pb.HistoryDeleteDirectives history_delete_directives = 2;</code>
   */
  public org.chromium.components.sync.protocol.HistoryDeleteDirectives getHistoryDeleteDirectives() {
    return historyDeleteDirectives_ == null ? org.chromium.components.sync.protocol.HistoryDeleteDirectives.getDefaultInstance() : historyDeleteDirectives_;
  }
  /**
   * <code>optional .sync_pb.HistoryDeleteDirectives history_delete_directives = 2;</code>
   */
  private void setHistoryDeleteDirectives(org.chromium.components.sync.protocol.HistoryDeleteDirectives value) {
    if (value == null) {
      throw new NullPointerException();
    }
    historyDeleteDirectives_ = value;
    bitField0_ |= 0x00000002;
    }
  /**
   * <code>optional .sync_pb.HistoryDeleteDirectives history_delete_directives = 2;</code>
   */
  private void setHistoryDeleteDirectives(
      org.chromium.components.sync.protocol.HistoryDeleteDirectives.Builder builderForValue) {
    historyDeleteDirectives_ = builderForValue.build();
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>optional .sync_pb.HistoryDeleteDirectives history_delete_directives = 2;</code>
   */
  private void mergeHistoryDeleteDirectives(org.chromium.components.sync.protocol.HistoryDeleteDirectives value) {
    if (historyDeleteDirectives_ != null &&
        historyDeleteDirectives_ != org.chromium.components.sync.protocol.HistoryDeleteDirectives.getDefaultInstance()) {
      historyDeleteDirectives_ =
        org.chromium.components.sync.protocol.HistoryDeleteDirectives.newBuilder(historyDeleteDirectives_).mergeFrom(value).buildPartial();
    } else {
      historyDeleteDirectives_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>optional .sync_pb.HistoryDeleteDirectives history_delete_directives = 2;</code>
   */
  private void clearHistoryDeleteDirectives() {  historyDeleteDirectives_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static final int AUTOFILL_CULLING_FIELD_NUMBER = 3;
  private org.chromium.components.sync.protocol.AutofillCullingFlags autofillCulling_;
  /**
   * <code>optional .sync_pb.AutofillCullingFlags autofill_culling = 3;</code>
   */
  public boolean hasAutofillCulling() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional .sync_pb.AutofillCullingFlags autofill_culling = 3;</code>
   */
  public org.chromium.components.sync.protocol.AutofillCullingFlags getAutofillCulling() {
    return autofillCulling_ == null ? org.chromium.components.sync.protocol.AutofillCullingFlags.getDefaultInstance() : autofillCulling_;
  }
  /**
   * <code>optional .sync_pb.AutofillCullingFlags autofill_culling = 3;</code>
   */
  private void setAutofillCulling(org.chromium.components.sync.protocol.AutofillCullingFlags value) {
    if (value == null) {
      throw new NullPointerException();
    }
    autofillCulling_ = value;
    bitField0_ |= 0x00000004;
    }
  /**
   * <code>optional .sync_pb.AutofillCullingFlags autofill_culling = 3;</code>
   */
  private void setAutofillCulling(
      org.chromium.components.sync.protocol.AutofillCullingFlags.Builder builderForValue) {
    autofillCulling_ = builderForValue.build();
    bitField0_ |= 0x00000004;
  }
  /**
   * <code>optional .sync_pb.AutofillCullingFlags autofill_culling = 3;</code>
   */
  private void mergeAutofillCulling(org.chromium.components.sync.protocol.AutofillCullingFlags value) {
    if (autofillCulling_ != null &&
        autofillCulling_ != org.chromium.components.sync.protocol.AutofillCullingFlags.getDefaultInstance()) {
      autofillCulling_ =
        org.chromium.components.sync.protocol.AutofillCullingFlags.newBuilder(autofillCulling_).mergeFrom(value).buildPartial();
    } else {
      autofillCulling_ = value;
    }
    bitField0_ |= 0x00000004;
  }
  /**
   * <code>optional .sync_pb.AutofillCullingFlags autofill_culling = 3;</code>
   */
  private void clearAutofillCulling() {  autofillCulling_ = null;
    bitField0_ = (bitField0_ & ~0x00000004);
  }

  public static final int FAVICON_SYNC_FIELD_NUMBER = 4;
  private org.chromium.components.sync.protocol.FaviconSyncFlags faviconSync_;
  /**
   * <code>optional .sync_pb.FaviconSyncFlags favicon_sync = 4;</code>
   */
  public boolean hasFaviconSync() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional .sync_pb.FaviconSyncFlags favicon_sync = 4;</code>
   */
  public org.chromium.components.sync.protocol.FaviconSyncFlags getFaviconSync() {
    return faviconSync_ == null ? org.chromium.components.sync.protocol.FaviconSyncFlags.getDefaultInstance() : faviconSync_;
  }
  /**
   * <code>optional .sync_pb.FaviconSyncFlags favicon_sync = 4;</code>
   */
  private void setFaviconSync(org.chromium.components.sync.protocol.FaviconSyncFlags value) {
    if (value == null) {
      throw new NullPointerException();
    }
    faviconSync_ = value;
    bitField0_ |= 0x00000008;
    }
  /**
   * <code>optional .sync_pb.FaviconSyncFlags favicon_sync = 4;</code>
   */
  private void setFaviconSync(
      org.chromium.components.sync.protocol.FaviconSyncFlags.Builder builderForValue) {
    faviconSync_ = builderForValue.build();
    bitField0_ |= 0x00000008;
  }
  /**
   * <code>optional .sync_pb.FaviconSyncFlags favicon_sync = 4;</code>
   */
  private void mergeFaviconSync(org.chromium.components.sync.protocol.FaviconSyncFlags value) {
    if (faviconSync_ != null &&
        faviconSync_ != org.chromium.components.sync.protocol.FaviconSyncFlags.getDefaultInstance()) {
      faviconSync_ =
        org.chromium.components.sync.protocol.FaviconSyncFlags.newBuilder(faviconSync_).mergeFrom(value).buildPartial();
    } else {
      faviconSync_ = value;
    }
    bitField0_ |= 0x00000008;
  }
  /**
   * <code>optional .sync_pb.FaviconSyncFlags favicon_sync = 4;</code>
   */
  private void clearFaviconSync() {  faviconSync_ = null;
    bitField0_ = (bitField0_ & ~0x00000008);
  }

  public static final int PRE_COMMIT_UPDATE_AVOIDANCE_FIELD_NUMBER = 5;
  private org.chromium.components.sync.protocol.PreCommitUpdateAvoidanceFlags preCommitUpdateAvoidance_;
  /**
   * <code>optional .sync_pb.PreCommitUpdateAvoidanceFlags pre_commit_update_avoidance = 5;</code>
   */
  public boolean hasPreCommitUpdateAvoidance() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional .sync_pb.PreCommitUpdateAvoidanceFlags pre_commit_update_avoidance = 5;</code>
   */
  public org.chromium.components.sync.protocol.PreCommitUpdateAvoidanceFlags getPreCommitUpdateAvoidance() {
    return preCommitUpdateAvoidance_ == null ? org.chromium.components.sync.protocol.PreCommitUpdateAvoidanceFlags.getDefaultInstance() : preCommitUpdateAvoidance_;
  }
  /**
   * <code>optional .sync_pb.PreCommitUpdateAvoidanceFlags pre_commit_update_avoidance = 5;</code>
   */
  private void setPreCommitUpdateAvoidance(org.chromium.components.sync.protocol.PreCommitUpdateAvoidanceFlags value) {
    if (value == null) {
      throw new NullPointerException();
    }
    preCommitUpdateAvoidance_ = value;
    bitField0_ |= 0x00000010;
    }
  /**
   * <code>optional .sync_pb.PreCommitUpdateAvoidanceFlags pre_commit_update_avoidance = 5;</code>
   */
  private void setPreCommitUpdateAvoidance(
      org.chromium.components.sync.protocol.PreCommitUpdateAvoidanceFlags.Builder builderForValue) {
    preCommitUpdateAvoidance_ = builderForValue.build();
    bitField0_ |= 0x00000010;
  }
  /**
   * <code>optional .sync_pb.PreCommitUpdateAvoidanceFlags pre_commit_update_avoidance = 5;</code>
   */
  private void mergePreCommitUpdateAvoidance(org.chromium.components.sync.protocol.PreCommitUpdateAvoidanceFlags value) {
    if (preCommitUpdateAvoidance_ != null &&
        preCommitUpdateAvoidance_ != org.chromium.components.sync.protocol.PreCommitUpdateAvoidanceFlags.getDefaultInstance()) {
      preCommitUpdateAvoidance_ =
        org.chromium.components.sync.protocol.PreCommitUpdateAvoidanceFlags.newBuilder(preCommitUpdateAvoidance_).mergeFrom(value).buildPartial();
    } else {
      preCommitUpdateAvoidance_ = value;
    }
    bitField0_ |= 0x00000010;
  }
  /**
   * <code>optional .sync_pb.PreCommitUpdateAvoidanceFlags pre_commit_update_avoidance = 5;</code>
   */
  private void clearPreCommitUpdateAvoidance() {  preCommitUpdateAvoidance_ = null;
    bitField0_ = (bitField0_ & ~0x00000010);
  }

  public static final int GCM_CHANNEL_FIELD_NUMBER = 6;
  private org.chromium.components.sync.protocol.GcmChannelFlags gcmChannel_;
  /**
   * <code>optional .sync_pb.GcmChannelFlags gcm_channel = 6;</code>
   */
  public boolean hasGcmChannel() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional .sync_pb.GcmChannelFlags gcm_channel = 6;</code>
   */
  public org.chromium.components.sync.protocol.GcmChannelFlags getGcmChannel() {
    return gcmChannel_ == null ? org.chromium.components.sync.protocol.GcmChannelFlags.getDefaultInstance() : gcmChannel_;
  }
  /**
   * <code>optional .sync_pb.GcmChannelFlags gcm_channel = 6;</code>
   */
  private void setGcmChannel(org.chromium.components.sync.protocol.GcmChannelFlags value) {
    if (value == null) {
      throw new NullPointerException();
    }
    gcmChannel_ = value;
    bitField0_ |= 0x00000020;
    }
  /**
   * <code>optional .sync_pb.GcmChannelFlags gcm_channel = 6;</code>
   */
  private void setGcmChannel(
      org.chromium.components.sync.protocol.GcmChannelFlags.Builder builderForValue) {
    gcmChannel_ = builderForValue.build();
    bitField0_ |= 0x00000020;
  }
  /**
   * <code>optional .sync_pb.GcmChannelFlags gcm_channel = 6;</code>
   */
  private void mergeGcmChannel(org.chromium.components.sync.protocol.GcmChannelFlags value) {
    if (gcmChannel_ != null &&
        gcmChannel_ != org.chromium.components.sync.protocol.GcmChannelFlags.getDefaultInstance()) {
      gcmChannel_ =
        org.chromium.components.sync.protocol.GcmChannelFlags.newBuilder(gcmChannel_).mergeFrom(value).buildPartial();
    } else {
      gcmChannel_ = value;
    }
    bitField0_ |= 0x00000020;
  }
  /**
   * <code>optional .sync_pb.GcmChannelFlags gcm_channel = 6;</code>
   */
  private void clearGcmChannel() {  gcmChannel_ = null;
    bitField0_ = (bitField0_ & ~0x00000020);
  }

  public static final int OBSOLETE_ENHANCED_BOOKMARKS_FIELD_NUMBER = 7;
  private org.chromium.components.sync.protocol.EnhancedBookmarksFlags obsoleteEnhancedBookmarks_;
  /**
   * <pre>
   * No longer used as of M43.
   * </pre>
   *
   * <code>optional .sync_pb.EnhancedBookmarksFlags obsolete_enhanced_bookmarks = 7;</code>
   */
  public boolean hasObsoleteEnhancedBookmarks() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <pre>
   * No longer used as of M43.
   * </pre>
   *
   * <code>optional .sync_pb.EnhancedBookmarksFlags obsolete_enhanced_bookmarks = 7;</code>
   */
  public org.chromium.components.sync.protocol.EnhancedBookmarksFlags getObsoleteEnhancedBookmarks() {
    return obsoleteEnhancedBookmarks_ == null ? org.chromium.components.sync.protocol.EnhancedBookmarksFlags.getDefaultInstance() : obsoleteEnhancedBookmarks_;
  }
  /**
   * <pre>
   * No longer used as of M43.
   * </pre>
   *
   * <code>optional .sync_pb.EnhancedBookmarksFlags obsolete_enhanced_bookmarks = 7;</code>
   */
  private void setObsoleteEnhancedBookmarks(org.chromium.components.sync.protocol.EnhancedBookmarksFlags value) {
    if (value == null) {
      throw new NullPointerException();
    }
    obsoleteEnhancedBookmarks_ = value;
    bitField0_ |= 0x00000040;
    }
  /**
   * <pre>
   * No longer used as of M43.
   * </pre>
   *
   * <code>optional .sync_pb.EnhancedBookmarksFlags obsolete_enhanced_bookmarks = 7;</code>
   */
  private void setObsoleteEnhancedBookmarks(
      org.chromium.components.sync.protocol.EnhancedBookmarksFlags.Builder builderForValue) {
    obsoleteEnhancedBookmarks_ = builderForValue.build();
    bitField0_ |= 0x00000040;
  }
  /**
   * <pre>
   * No longer used as of M43.
   * </pre>
   *
   * <code>optional .sync_pb.EnhancedBookmarksFlags obsolete_enhanced_bookmarks = 7;</code>
   */
  private void mergeObsoleteEnhancedBookmarks(org.chromium.components.sync.protocol.EnhancedBookmarksFlags value) {
    if (obsoleteEnhancedBookmarks_ != null &&
        obsoleteEnhancedBookmarks_ != org.chromium.components.sync.protocol.EnhancedBookmarksFlags.getDefaultInstance()) {
      obsoleteEnhancedBookmarks_ =
        org.chromium.components.sync.protocol.EnhancedBookmarksFlags.newBuilder(obsoleteEnhancedBookmarks_).mergeFrom(value).buildPartial();
    } else {
      obsoleteEnhancedBookmarks_ = value;
    }
    bitField0_ |= 0x00000040;
  }
  /**
   * <pre>
   * No longer used as of M43.
   * </pre>
   *
   * <code>optional .sync_pb.EnhancedBookmarksFlags obsolete_enhanced_bookmarks = 7;</code>
   */
  private void clearObsoleteEnhancedBookmarks() {  obsoleteEnhancedBookmarks_ = null;
    bitField0_ = (bitField0_ & ~0x00000040);
  }

  public static final int GCM_INVALIDATIONS_FIELD_NUMBER = 8;
  private org.chromium.components.sync.protocol.GcmInvalidationsFlags gcmInvalidations_;
  /**
   * <pre>
   * No longer used as of M72.
   * </pre>
   *
   * <code>optional .sync_pb.GcmInvalidationsFlags gcm_invalidations = 8;</code>
   */
  public boolean hasGcmInvalidations() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <pre>
   * No longer used as of M72.
   * </pre>
   *
   * <code>optional .sync_pb.GcmInvalidationsFlags gcm_invalidations = 8;</code>
   */
  public org.chromium.components.sync.protocol.GcmInvalidationsFlags getGcmInvalidations() {
    return gcmInvalidations_ == null ? org.chromium.components.sync.protocol.GcmInvalidationsFlags.getDefaultInstance() : gcmInvalidations_;
  }
  /**
   * <pre>
   * No longer used as of M72.
   * </pre>
   *
   * <code>optional .sync_pb.GcmInvalidationsFlags gcm_invalidations = 8;</code>
   */
  private void setGcmInvalidations(org.chromium.components.sync.protocol.GcmInvalidationsFlags value) {
    if (value == null) {
      throw new NullPointerException();
    }
    gcmInvalidations_ = value;
    bitField0_ |= 0x00000080;
    }
  /**
   * <pre>
   * No longer used as of M72.
   * </pre>
   *
   * <code>optional .sync_pb.GcmInvalidationsFlags gcm_invalidations = 8;</code>
   */
  private void setGcmInvalidations(
      org.chromium.components.sync.protocol.GcmInvalidationsFlags.Builder builderForValue) {
    gcmInvalidations_ = builderForValue.build();
    bitField0_ |= 0x00000080;
  }
  /**
   * <pre>
   * No longer used as of M72.
   * </pre>
   *
   * <code>optional .sync_pb.GcmInvalidationsFlags gcm_invalidations = 8;</code>
   */
  private void mergeGcmInvalidations(org.chromium.components.sync.protocol.GcmInvalidationsFlags value) {
    if (gcmInvalidations_ != null &&
        gcmInvalidations_ != org.chromium.components.sync.protocol.GcmInvalidationsFlags.getDefaultInstance()) {
      gcmInvalidations_ =
        org.chromium.components.sync.protocol.GcmInvalidationsFlags.newBuilder(gcmInvalidations_).mergeFrom(value).buildPartial();
    } else {
      gcmInvalidations_ = value;
    }
    bitField0_ |= 0x00000080;
  }
  /**
   * <pre>
   * No longer used as of M72.
   * </pre>
   *
   * <code>optional .sync_pb.GcmInvalidationsFlags gcm_invalidations = 8;</code>
   */
  private void clearGcmInvalidations() {  gcmInvalidations_ = null;
    bitField0_ = (bitField0_ & ~0x00000080);
  }

  public static final int OBSOLETE_WALLET_SYNC_FIELD_NUMBER = 9;
  private org.chromium.components.sync.protocol.WalletSyncFlags obsoleteWalletSync_;
  /**
   * <pre>
   * No longer used as of M51.
   * </pre>
   *
   * <code>optional .sync_pb.WalletSyncFlags obsolete_wallet_sync = 9;</code>
   */
  public boolean hasObsoleteWalletSync() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <pre>
   * No longer used as of M51.
   * </pre>
   *
   * <code>optional .sync_pb.WalletSyncFlags obsolete_wallet_sync = 9;</code>
   */
  public org.chromium.components.sync.protocol.WalletSyncFlags getObsoleteWalletSync() {
    return obsoleteWalletSync_ == null ? org.chromium.components.sync.protocol.WalletSyncFlags.getDefaultInstance() : obsoleteWalletSync_;
  }
  /**
   * <pre>
   * No longer used as of M51.
   * </pre>
   *
   * <code>optional .sync_pb.WalletSyncFlags obsolete_wallet_sync = 9;</code>
   */
  private void setObsoleteWalletSync(org.chromium.components.sync.protocol.WalletSyncFlags value) {
    if (value == null) {
      throw new NullPointerException();
    }
    obsoleteWalletSync_ = value;
    bitField0_ |= 0x00000100;
    }
  /**
   * <pre>
   * No longer used as of M51.
   * </pre>
   *
   * <code>optional .sync_pb.WalletSyncFlags obsolete_wallet_sync = 9;</code>
   */
  private void setObsoleteWalletSync(
      org.chromium.components.sync.protocol.WalletSyncFlags.Builder builderForValue) {
    obsoleteWalletSync_ = builderForValue.build();
    bitField0_ |= 0x00000100;
  }
  /**
   * <pre>
   * No longer used as of M51.
   * </pre>
   *
   * <code>optional .sync_pb.WalletSyncFlags obsolete_wallet_sync = 9;</code>
   */
  private void mergeObsoleteWalletSync(org.chromium.components.sync.protocol.WalletSyncFlags value) {
    if (obsoleteWalletSync_ != null &&
        obsoleteWalletSync_ != org.chromium.components.sync.protocol.WalletSyncFlags.getDefaultInstance()) {
      obsoleteWalletSync_ =
        org.chromium.components.sync.protocol.WalletSyncFlags.newBuilder(obsoleteWalletSync_).mergeFrom(value).buildPartial();
    } else {
      obsoleteWalletSync_ = value;
    }
    bitField0_ |= 0x00000100;
  }
  /**
   * <pre>
   * No longer used as of M51.
   * </pre>
   *
   * <code>optional .sync_pb.WalletSyncFlags obsolete_wallet_sync = 9;</code>
   */
  private void clearObsoleteWalletSync() {  obsoleteWalletSync_ = null;
    bitField0_ = (bitField0_ & ~0x00000100);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, getKeystoreEncryption());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, getHistoryDeleteDirectives());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeMessage(3, getAutofillCulling());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeMessage(4, getFaviconSync());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeMessage(5, getPreCommitUpdateAvoidance());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeMessage(6, getGcmChannel());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeMessage(7, getObsoleteEnhancedBookmarks());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeMessage(8, getGcmInvalidations());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeMessage(9, getObsoleteWalletSync());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getKeystoreEncryption());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getHistoryDeleteDirectives());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAutofillCulling());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getFaviconSync());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getPreCommitUpdateAvoidance());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getGcmChannel());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getObsoleteEnhancedBookmarks());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getGcmInvalidations());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getObsoleteWalletSync());
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static org.chromium.components.sync.protocol.ExperimentsSpecifics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.ExperimentsSpecifics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ExperimentsSpecifics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.ExperimentsSpecifics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ExperimentsSpecifics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.ExperimentsSpecifics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ExperimentsSpecifics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.ExperimentsSpecifics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ExperimentsSpecifics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.ExperimentsSpecifics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.chromium.components.sync.protocol.ExperimentsSpecifics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * Contains one flag or set of related flags.  Each node of the experiments type
   * will have a unique_client_tag identifying which flags it contains.  By
   * convention, the tag name should match the sub-message name.
   * </pre>
   *
   * Protobuf type {@code sync_pb.ExperimentsSpecifics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.components.sync.protocol.ExperimentsSpecifics, Builder> implements
      // @@protoc_insertion_point(builder_implements:sync_pb.ExperimentsSpecifics)
      org.chromium.components.sync.protocol.ExperimentsSpecificsOrBuilder {
    // Construct using org.chromium.components.sync.protocol.ExperimentsSpecifics.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .sync_pb.KeystoreEncryptionFlags keystore_encryption = 1;</code>
     */
    public boolean hasKeystoreEncryption() {
      return instance.hasKeystoreEncryption();
    }
    /**
     * <code>optional .sync_pb.KeystoreEncryptionFlags keystore_encryption = 1;</code>
     */
    public org.chromium.components.sync.protocol.KeystoreEncryptionFlags getKeystoreEncryption() {
      return instance.getKeystoreEncryption();
    }
    /**
     * <code>optional .sync_pb.KeystoreEncryptionFlags keystore_encryption = 1;</code>
     */
    public Builder setKeystoreEncryption(org.chromium.components.sync.protocol.KeystoreEncryptionFlags value) {
      copyOnWrite();
      instance.setKeystoreEncryption(value);
      return this;
      }
    /**
     * <code>optional .sync_pb.KeystoreEncryptionFlags keystore_encryption = 1;</code>
     */
    public Builder setKeystoreEncryption(
        org.chromium.components.sync.protocol.KeystoreEncryptionFlags.Builder builderForValue) {
      copyOnWrite();
      instance.setKeystoreEncryption(builderForValue);
      return this;
    }
    /**
     * <code>optional .sync_pb.KeystoreEncryptionFlags keystore_encryption = 1;</code>
     */
    public Builder mergeKeystoreEncryption(org.chromium.components.sync.protocol.KeystoreEncryptionFlags value) {
      copyOnWrite();
      instance.mergeKeystoreEncryption(value);
      return this;
    }
    /**
     * <code>optional .sync_pb.KeystoreEncryptionFlags keystore_encryption = 1;</code>
     */
    public Builder clearKeystoreEncryption() {  copyOnWrite();
      instance.clearKeystoreEncryption();
      return this;
    }

    /**
     * <code>optional .sync_pb.HistoryDeleteDirectives history_delete_directives = 2;</code>
     */
    public boolean hasHistoryDeleteDirectives() {
      return instance.hasHistoryDeleteDirectives();
    }
    /**
     * <code>optional .sync_pb.HistoryDeleteDirectives history_delete_directives = 2;</code>
     */
    public org.chromium.components.sync.protocol.HistoryDeleteDirectives getHistoryDeleteDirectives() {
      return instance.getHistoryDeleteDirectives();
    }
    /**
     * <code>optional .sync_pb.HistoryDeleteDirectives history_delete_directives = 2;</code>
     */
    public Builder setHistoryDeleteDirectives(org.chromium.components.sync.protocol.HistoryDeleteDirectives value) {
      copyOnWrite();
      instance.setHistoryDeleteDirectives(value);
      return this;
      }
    /**
     * <code>optional .sync_pb.HistoryDeleteDirectives history_delete_directives = 2;</code>
     */
    public Builder setHistoryDeleteDirectives(
        org.chromium.components.sync.protocol.HistoryDeleteDirectives.Builder builderForValue) {
      copyOnWrite();
      instance.setHistoryDeleteDirectives(builderForValue);
      return this;
    }
    /**
     * <code>optional .sync_pb.HistoryDeleteDirectives history_delete_directives = 2;</code>
     */
    public Builder mergeHistoryDeleteDirectives(org.chromium.components.sync.protocol.HistoryDeleteDirectives value) {
      copyOnWrite();
      instance.mergeHistoryDeleteDirectives(value);
      return this;
    }
    /**
     * <code>optional .sync_pb.HistoryDeleteDirectives history_delete_directives = 2;</code>
     */
    public Builder clearHistoryDeleteDirectives() {  copyOnWrite();
      instance.clearHistoryDeleteDirectives();
      return this;
    }

    /**
     * <code>optional .sync_pb.AutofillCullingFlags autofill_culling = 3;</code>
     */
    public boolean hasAutofillCulling() {
      return instance.hasAutofillCulling();
    }
    /**
     * <code>optional .sync_pb.AutofillCullingFlags autofill_culling = 3;</code>
     */
    public org.chromium.components.sync.protocol.AutofillCullingFlags getAutofillCulling() {
      return instance.getAutofillCulling();
    }
    /**
     * <code>optional .sync_pb.AutofillCullingFlags autofill_culling = 3;</code>
     */
    public Builder setAutofillCulling(org.chromium.components.sync.protocol.AutofillCullingFlags value) {
      copyOnWrite();
      instance.setAutofillCulling(value);
      return this;
      }
    /**
     * <code>optional .sync_pb.AutofillCullingFlags autofill_culling = 3;</code>
     */
    public Builder setAutofillCulling(
        org.chromium.components.sync.protocol.AutofillCullingFlags.Builder builderForValue) {
      copyOnWrite();
      instance.setAutofillCulling(builderForValue);
      return this;
    }
    /**
     * <code>optional .sync_pb.AutofillCullingFlags autofill_culling = 3;</code>
     */
    public Builder mergeAutofillCulling(org.chromium.components.sync.protocol.AutofillCullingFlags value) {
      copyOnWrite();
      instance.mergeAutofillCulling(value);
      return this;
    }
    /**
     * <code>optional .sync_pb.AutofillCullingFlags autofill_culling = 3;</code>
     */
    public Builder clearAutofillCulling() {  copyOnWrite();
      instance.clearAutofillCulling();
      return this;
    }

    /**
     * <code>optional .sync_pb.FaviconSyncFlags favicon_sync = 4;</code>
     */
    public boolean hasFaviconSync() {
      return instance.hasFaviconSync();
    }
    /**
     * <code>optional .sync_pb.FaviconSyncFlags favicon_sync = 4;</code>
     */
    public org.chromium.components.sync.protocol.FaviconSyncFlags getFaviconSync() {
      return instance.getFaviconSync();
    }
    /**
     * <code>optional .sync_pb.FaviconSyncFlags favicon_sync = 4;</code>
     */
    public Builder setFaviconSync(org.chromium.components.sync.protocol.FaviconSyncFlags value) {
      copyOnWrite();
      instance.setFaviconSync(value);
      return this;
      }
    /**
     * <code>optional .sync_pb.FaviconSyncFlags favicon_sync = 4;</code>
     */
    public Builder setFaviconSync(
        org.chromium.components.sync.protocol.FaviconSyncFlags.Builder builderForValue) {
      copyOnWrite();
      instance.setFaviconSync(builderForValue);
      return this;
    }
    /**
     * <code>optional .sync_pb.FaviconSyncFlags favicon_sync = 4;</code>
     */
    public Builder mergeFaviconSync(org.chromium.components.sync.protocol.FaviconSyncFlags value) {
      copyOnWrite();
      instance.mergeFaviconSync(value);
      return this;
    }
    /**
     * <code>optional .sync_pb.FaviconSyncFlags favicon_sync = 4;</code>
     */
    public Builder clearFaviconSync() {  copyOnWrite();
      instance.clearFaviconSync();
      return this;
    }

    /**
     * <code>optional .sync_pb.PreCommitUpdateAvoidanceFlags pre_commit_update_avoidance = 5;</code>
     */
    public boolean hasPreCommitUpdateAvoidance() {
      return instance.hasPreCommitUpdateAvoidance();
    }
    /**
     * <code>optional .sync_pb.PreCommitUpdateAvoidanceFlags pre_commit_update_avoidance = 5;</code>
     */
    public org.chromium.components.sync.protocol.PreCommitUpdateAvoidanceFlags getPreCommitUpdateAvoidance() {
      return instance.getPreCommitUpdateAvoidance();
    }
    /**
     * <code>optional .sync_pb.PreCommitUpdateAvoidanceFlags pre_commit_update_avoidance = 5;</code>
     */
    public Builder setPreCommitUpdateAvoidance(org.chromium.components.sync.protocol.PreCommitUpdateAvoidanceFlags value) {
      copyOnWrite();
      instance.setPreCommitUpdateAvoidance(value);
      return this;
      }
    /**
     * <code>optional .sync_pb.PreCommitUpdateAvoidanceFlags pre_commit_update_avoidance = 5;</code>
     */
    public Builder setPreCommitUpdateAvoidance(
        org.chromium.components.sync.protocol.PreCommitUpdateAvoidanceFlags.Builder builderForValue) {
      copyOnWrite();
      instance.setPreCommitUpdateAvoidance(builderForValue);
      return this;
    }
    /**
     * <code>optional .sync_pb.PreCommitUpdateAvoidanceFlags pre_commit_update_avoidance = 5;</code>
     */
    public Builder mergePreCommitUpdateAvoidance(org.chromium.components.sync.protocol.PreCommitUpdateAvoidanceFlags value) {
      copyOnWrite();
      instance.mergePreCommitUpdateAvoidance(value);
      return this;
    }
    /**
     * <code>optional .sync_pb.PreCommitUpdateAvoidanceFlags pre_commit_update_avoidance = 5;</code>
     */
    public Builder clearPreCommitUpdateAvoidance() {  copyOnWrite();
      instance.clearPreCommitUpdateAvoidance();
      return this;
    }

    /**
     * <code>optional .sync_pb.GcmChannelFlags gcm_channel = 6;</code>
     */
    public boolean hasGcmChannel() {
      return instance.hasGcmChannel();
    }
    /**
     * <code>optional .sync_pb.GcmChannelFlags gcm_channel = 6;</code>
     */
    public org.chromium.components.sync.protocol.GcmChannelFlags getGcmChannel() {
      return instance.getGcmChannel();
    }
    /**
     * <code>optional .sync_pb.GcmChannelFlags gcm_channel = 6;</code>
     */
    public Builder setGcmChannel(org.chromium.components.sync.protocol.GcmChannelFlags value) {
      copyOnWrite();
      instance.setGcmChannel(value);
      return this;
      }
    /**
     * <code>optional .sync_pb.GcmChannelFlags gcm_channel = 6;</code>
     */
    public Builder setGcmChannel(
        org.chromium.components.sync.protocol.GcmChannelFlags.Builder builderForValue) {
      copyOnWrite();
      instance.setGcmChannel(builderForValue);
      return this;
    }
    /**
     * <code>optional .sync_pb.GcmChannelFlags gcm_channel = 6;</code>
     */
    public Builder mergeGcmChannel(org.chromium.components.sync.protocol.GcmChannelFlags value) {
      copyOnWrite();
      instance.mergeGcmChannel(value);
      return this;
    }
    /**
     * <code>optional .sync_pb.GcmChannelFlags gcm_channel = 6;</code>
     */
    public Builder clearGcmChannel() {  copyOnWrite();
      instance.clearGcmChannel();
      return this;
    }

    /**
     * <pre>
     * No longer used as of M43.
     * </pre>
     *
     * <code>optional .sync_pb.EnhancedBookmarksFlags obsolete_enhanced_bookmarks = 7;</code>
     */
    public boolean hasObsoleteEnhancedBookmarks() {
      return instance.hasObsoleteEnhancedBookmarks();
    }
    /**
     * <pre>
     * No longer used as of M43.
     * </pre>
     *
     * <code>optional .sync_pb.EnhancedBookmarksFlags obsolete_enhanced_bookmarks = 7;</code>
     */
    public org.chromium.components.sync.protocol.EnhancedBookmarksFlags getObsoleteEnhancedBookmarks() {
      return instance.getObsoleteEnhancedBookmarks();
    }
    /**
     * <pre>
     * No longer used as of M43.
     * </pre>
     *
     * <code>optional .sync_pb.EnhancedBookmarksFlags obsolete_enhanced_bookmarks = 7;</code>
     */
    public Builder setObsoleteEnhancedBookmarks(org.chromium.components.sync.protocol.EnhancedBookmarksFlags value) {
      copyOnWrite();
      instance.setObsoleteEnhancedBookmarks(value);
      return this;
      }
    /**
     * <pre>
     * No longer used as of M43.
     * </pre>
     *
     * <code>optional .sync_pb.EnhancedBookmarksFlags obsolete_enhanced_bookmarks = 7;</code>
     */
    public Builder setObsoleteEnhancedBookmarks(
        org.chromium.components.sync.protocol.EnhancedBookmarksFlags.Builder builderForValue) {
      copyOnWrite();
      instance.setObsoleteEnhancedBookmarks(builderForValue);
      return this;
    }
    /**
     * <pre>
     * No longer used as of M43.
     * </pre>
     *
     * <code>optional .sync_pb.EnhancedBookmarksFlags obsolete_enhanced_bookmarks = 7;</code>
     */
    public Builder mergeObsoleteEnhancedBookmarks(org.chromium.components.sync.protocol.EnhancedBookmarksFlags value) {
      copyOnWrite();
      instance.mergeObsoleteEnhancedBookmarks(value);
      return this;
    }
    /**
     * <pre>
     * No longer used as of M43.
     * </pre>
     *
     * <code>optional .sync_pb.EnhancedBookmarksFlags obsolete_enhanced_bookmarks = 7;</code>
     */
    public Builder clearObsoleteEnhancedBookmarks() {  copyOnWrite();
      instance.clearObsoleteEnhancedBookmarks();
      return this;
    }

    /**
     * <pre>
     * No longer used as of M72.
     * </pre>
     *
     * <code>optional .sync_pb.GcmInvalidationsFlags gcm_invalidations = 8;</code>
     */
    public boolean hasGcmInvalidations() {
      return instance.hasGcmInvalidations();
    }
    /**
     * <pre>
     * No longer used as of M72.
     * </pre>
     *
     * <code>optional .sync_pb.GcmInvalidationsFlags gcm_invalidations = 8;</code>
     */
    public org.chromium.components.sync.protocol.GcmInvalidationsFlags getGcmInvalidations() {
      return instance.getGcmInvalidations();
    }
    /**
     * <pre>
     * No longer used as of M72.
     * </pre>
     *
     * <code>optional .sync_pb.GcmInvalidationsFlags gcm_invalidations = 8;</code>
     */
    public Builder setGcmInvalidations(org.chromium.components.sync.protocol.GcmInvalidationsFlags value) {
      copyOnWrite();
      instance.setGcmInvalidations(value);
      return this;
      }
    /**
     * <pre>
     * No longer used as of M72.
     * </pre>
     *
     * <code>optional .sync_pb.GcmInvalidationsFlags gcm_invalidations = 8;</code>
     */
    public Builder setGcmInvalidations(
        org.chromium.components.sync.protocol.GcmInvalidationsFlags.Builder builderForValue) {
      copyOnWrite();
      instance.setGcmInvalidations(builderForValue);
      return this;
    }
    /**
     * <pre>
     * No longer used as of M72.
     * </pre>
     *
     * <code>optional .sync_pb.GcmInvalidationsFlags gcm_invalidations = 8;</code>
     */
    public Builder mergeGcmInvalidations(org.chromium.components.sync.protocol.GcmInvalidationsFlags value) {
      copyOnWrite();
      instance.mergeGcmInvalidations(value);
      return this;
    }
    /**
     * <pre>
     * No longer used as of M72.
     * </pre>
     *
     * <code>optional .sync_pb.GcmInvalidationsFlags gcm_invalidations = 8;</code>
     */
    public Builder clearGcmInvalidations() {  copyOnWrite();
      instance.clearGcmInvalidations();
      return this;
    }

    /**
     * <pre>
     * No longer used as of M51.
     * </pre>
     *
     * <code>optional .sync_pb.WalletSyncFlags obsolete_wallet_sync = 9;</code>
     */
    public boolean hasObsoleteWalletSync() {
      return instance.hasObsoleteWalletSync();
    }
    /**
     * <pre>
     * No longer used as of M51.
     * </pre>
     *
     * <code>optional .sync_pb.WalletSyncFlags obsolete_wallet_sync = 9;</code>
     */
    public org.chromium.components.sync.protocol.WalletSyncFlags getObsoleteWalletSync() {
      return instance.getObsoleteWalletSync();
    }
    /**
     * <pre>
     * No longer used as of M51.
     * </pre>
     *
     * <code>optional .sync_pb.WalletSyncFlags obsolete_wallet_sync = 9;</code>
     */
    public Builder setObsoleteWalletSync(org.chromium.components.sync.protocol.WalletSyncFlags value) {
      copyOnWrite();
      instance.setObsoleteWalletSync(value);
      return this;
      }
    /**
     * <pre>
     * No longer used as of M51.
     * </pre>
     *
     * <code>optional .sync_pb.WalletSyncFlags obsolete_wallet_sync = 9;</code>
     */
    public Builder setObsoleteWalletSync(
        org.chromium.components.sync.protocol.WalletSyncFlags.Builder builderForValue) {
      copyOnWrite();
      instance.setObsoleteWalletSync(builderForValue);
      return this;
    }
    /**
     * <pre>
     * No longer used as of M51.
     * </pre>
     *
     * <code>optional .sync_pb.WalletSyncFlags obsolete_wallet_sync = 9;</code>
     */
    public Builder mergeObsoleteWalletSync(org.chromium.components.sync.protocol.WalletSyncFlags value) {
      copyOnWrite();
      instance.mergeObsoleteWalletSync(value);
      return this;
    }
    /**
     * <pre>
     * No longer used as of M51.
     * </pre>
     *
     * <code>optional .sync_pb.WalletSyncFlags obsolete_wallet_sync = 9;</code>
     */
    public Builder clearObsoleteWalletSync() {  copyOnWrite();
      instance.clearObsoleteWalletSync();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sync_pb.ExperimentsSpecifics)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.components.sync.protocol.ExperimentsSpecifics();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        org.chromium.components.sync.protocol.ExperimentsSpecifics other = (org.chromium.components.sync.protocol.ExperimentsSpecifics) arg1;
        keystoreEncryption_ = visitor.visitMessage(keystoreEncryption_, other.keystoreEncryption_);
        historyDeleteDirectives_ = visitor.visitMessage(historyDeleteDirectives_, other.historyDeleteDirectives_);
        autofillCulling_ = visitor.visitMessage(autofillCulling_, other.autofillCulling_);
        faviconSync_ = visitor.visitMessage(faviconSync_, other.faviconSync_);
        preCommitUpdateAvoidance_ = visitor.visitMessage(preCommitUpdateAvoidance_, other.preCommitUpdateAvoidance_);
        gcmChannel_ = visitor.visitMessage(gcmChannel_, other.gcmChannel_);
        obsoleteEnhancedBookmarks_ = visitor.visitMessage(obsoleteEnhancedBookmarks_, other.obsoleteEnhancedBookmarks_);
        gcmInvalidations_ = visitor.visitMessage(gcmInvalidations_, other.gcmInvalidations_);
        obsoleteWalletSync_ = visitor.visitMessage(obsoleteWalletSync_, other.obsoleteWalletSync_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 10: {
                org.chromium.components.sync.protocol.KeystoreEncryptionFlags.Builder subBuilder = null;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                  subBuilder = keystoreEncryption_.toBuilder();
                }
                keystoreEncryption_ = input.readMessage(org.chromium.components.sync.protocol.KeystoreEncryptionFlags.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(keystoreEncryption_);
                  keystoreEncryption_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000001;
                break;
              }
              case 18: {
                org.chromium.components.sync.protocol.HistoryDeleteDirectives.Builder subBuilder = null;
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                  subBuilder = historyDeleteDirectives_.toBuilder();
                }
                historyDeleteDirectives_ = input.readMessage(org.chromium.components.sync.protocol.HistoryDeleteDirectives.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(historyDeleteDirectives_);
                  historyDeleteDirectives_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000002;
                break;
              }
              case 26: {
                org.chromium.components.sync.protocol.AutofillCullingFlags.Builder subBuilder = null;
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                  subBuilder = autofillCulling_.toBuilder();
                }
                autofillCulling_ = input.readMessage(org.chromium.components.sync.protocol.AutofillCullingFlags.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(autofillCulling_);
                  autofillCulling_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000004;
                break;
              }
              case 34: {
                org.chromium.components.sync.protocol.FaviconSyncFlags.Builder subBuilder = null;
                if (((bitField0_ & 0x00000008) == 0x00000008)) {
                  subBuilder = faviconSync_.toBuilder();
                }
                faviconSync_ = input.readMessage(org.chromium.components.sync.protocol.FaviconSyncFlags.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(faviconSync_);
                  faviconSync_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000008;
                break;
              }
              case 42: {
                org.chromium.components.sync.protocol.PreCommitUpdateAvoidanceFlags.Builder subBuilder = null;
                if (((bitField0_ & 0x00000010) == 0x00000010)) {
                  subBuilder = preCommitUpdateAvoidance_.toBuilder();
                }
                preCommitUpdateAvoidance_ = input.readMessage(org.chromium.components.sync.protocol.PreCommitUpdateAvoidanceFlags.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(preCommitUpdateAvoidance_);
                  preCommitUpdateAvoidance_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000010;
                break;
              }
              case 50: {
                org.chromium.components.sync.protocol.GcmChannelFlags.Builder subBuilder = null;
                if (((bitField0_ & 0x00000020) == 0x00000020)) {
                  subBuilder = gcmChannel_.toBuilder();
                }
                gcmChannel_ = input.readMessage(org.chromium.components.sync.protocol.GcmChannelFlags.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(gcmChannel_);
                  gcmChannel_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000020;
                break;
              }
              case 58: {
                org.chromium.components.sync.protocol.EnhancedBookmarksFlags.Builder subBuilder = null;
                if (((bitField0_ & 0x00000040) == 0x00000040)) {
                  subBuilder = obsoleteEnhancedBookmarks_.toBuilder();
                }
                obsoleteEnhancedBookmarks_ = input.readMessage(org.chromium.components.sync.protocol.EnhancedBookmarksFlags.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(obsoleteEnhancedBookmarks_);
                  obsoleteEnhancedBookmarks_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000040;
                break;
              }
              case 66: {
                org.chromium.components.sync.protocol.GcmInvalidationsFlags.Builder subBuilder = null;
                if (((bitField0_ & 0x00000080) == 0x00000080)) {
                  subBuilder = gcmInvalidations_.toBuilder();
                }
                gcmInvalidations_ = input.readMessage(org.chromium.components.sync.protocol.GcmInvalidationsFlags.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(gcmInvalidations_);
                  gcmInvalidations_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000080;
                break;
              }
              case 74: {
                org.chromium.components.sync.protocol.WalletSyncFlags.Builder subBuilder = null;
                if (((bitField0_ & 0x00000100) == 0x00000100)) {
                  subBuilder = obsoleteWalletSync_.toBuilder();
                }
                obsoleteWalletSync_ = input.readMessage(org.chromium.components.sync.protocol.WalletSyncFlags.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(obsoleteWalletSync_);
                  obsoleteWalletSync_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000100;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (org.chromium.components.sync.protocol.ExperimentsSpecifics.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sync_pb.ExperimentsSpecifics)
  private static final org.chromium.components.sync.protocol.ExperimentsSpecifics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ExperimentsSpecifics();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static org.chromium.components.sync.protocol.ExperimentsSpecifics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ExperimentsSpecifics> PARSER;

  public static com.google.protobuf.Parser<ExperimentsSpecifics> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

