// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extension_setting_specifics.proto

package org.chromium.components.sync.protocol;

/**
 * <pre>
 * Properties of extension setting sync objects.
 * </pre>
 *
 * Protobuf type {@code sync_pb.ExtensionSettingSpecifics}
 */
public  final class ExtensionSettingSpecifics extends
    com.google.protobuf.GeneratedMessageLite<
        ExtensionSettingSpecifics, ExtensionSettingSpecifics.Builder> implements
    // @@protoc_insertion_point(message_implements:sync_pb.ExtensionSettingSpecifics)
    ExtensionSettingSpecificsOrBuilder {
  private ExtensionSettingSpecifics() {
    extensionId_ = "";
    key_ = "";
    value_ = "";
  }
  private int bitField0_;
  public static final int EXTENSION_ID_FIELD_NUMBER = 1;
  private java.lang.String extensionId_;
  /**
   * <pre>
   * Id of the extension the setting is for.
   * </pre>
   *
   * <code>optional string extension_id = 1;</code>
   */
  public boolean hasExtensionId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * Id of the extension the setting is for.
   * </pre>
   *
   * <code>optional string extension_id = 1;</code>
   */
  public java.lang.String getExtensionId() {
    return extensionId_;
  }
  /**
   * <pre>
   * Id of the extension the setting is for.
   * </pre>
   *
   * <code>optional string extension_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getExtensionIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(extensionId_);
  }
  /**
   * <pre>
   * Id of the extension the setting is for.
   * </pre>
   *
   * <code>optional string extension_id = 1;</code>
   */
  private void setExtensionId(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    extensionId_ = value;
  }
  /**
   * <pre>
   * Id of the extension the setting is for.
   * </pre>
   *
   * <code>optional string extension_id = 1;</code>
   */
  private void clearExtensionId() {
    bitField0_ = (bitField0_ & ~0x00000001);
    extensionId_ = getDefaultInstance().getExtensionId();
  }
  /**
   * <pre>
   * Id of the extension the setting is for.
   * </pre>
   *
   * <code>optional string extension_id = 1;</code>
   */
  private void setExtensionIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    extensionId_ = value.toStringUtf8();
  }

  public static final int KEY_FIELD_NUMBER = 2;
  private java.lang.String key_;
  /**
   * <pre>
   * Setting key.
   * </pre>
   *
   * <code>optional string key = 2;</code>
   */
  public boolean hasKey() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <pre>
   * Setting key.
   * </pre>
   *
   * <code>optional string key = 2;</code>
   */
  public java.lang.String getKey() {
    return key_;
  }
  /**
   * <pre>
   * Setting key.
   * </pre>
   *
   * <code>optional string key = 2;</code>
   */
  public com.google.protobuf.ByteString
      getKeyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(key_);
  }
  /**
   * <pre>
   * Setting key.
   * </pre>
   *
   * <code>optional string key = 2;</code>
   */
  private void setKey(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    key_ = value;
  }
  /**
   * <pre>
   * Setting key.
   * </pre>
   *
   * <code>optional string key = 2;</code>
   */
  private void clearKey() {
    bitField0_ = (bitField0_ & ~0x00000002);
    key_ = getDefaultInstance().getKey();
  }
  /**
   * <pre>
   * Setting key.
   * </pre>
   *
   * <code>optional string key = 2;</code>
   */
  private void setKeyBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
    key_ = value.toStringUtf8();
  }

  public static final int VALUE_FIELD_NUMBER = 3;
  private java.lang.String value_;
  /**
   * <pre>
   * Setting value serialized as JSON.
   * </pre>
   *
   * <code>optional string value = 3;</code>
   */
  public boolean hasValue() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <pre>
   * Setting value serialized as JSON.
   * </pre>
   *
   * <code>optional string value = 3;</code>
   */
  public java.lang.String getValue() {
    return value_;
  }
  /**
   * <pre>
   * Setting value serialized as JSON.
   * </pre>
   *
   * <code>optional string value = 3;</code>
   */
  public com.google.protobuf.ByteString
      getValueBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(value_);
  }
  /**
   * <pre>
   * Setting value serialized as JSON.
   * </pre>
   *
   * <code>optional string value = 3;</code>
   */
  private void setValue(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
    value_ = value;
  }
  /**
   * <pre>
   * Setting value serialized as JSON.
   * </pre>
   *
   * <code>optional string value = 3;</code>
   */
  private void clearValue() {
    bitField0_ = (bitField0_ & ~0x00000004);
    value_ = getDefaultInstance().getValue();
  }
  /**
   * <pre>
   * Setting value serialized as JSON.
   * </pre>
   *
   * <code>optional string value = 3;</code>
   */
  private void setValueBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
    value_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeString(1, getExtensionId());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeString(2, getKey());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeString(3, getValue());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getExtensionId());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getKey());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(3, getValue());
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static org.chromium.components.sync.protocol.ExtensionSettingSpecifics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.ExtensionSettingSpecifics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ExtensionSettingSpecifics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.ExtensionSettingSpecifics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ExtensionSettingSpecifics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.ExtensionSettingSpecifics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ExtensionSettingSpecifics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.ExtensionSettingSpecifics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ExtensionSettingSpecifics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.ExtensionSettingSpecifics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.chromium.components.sync.protocol.ExtensionSettingSpecifics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * Properties of extension setting sync objects.
   * </pre>
   *
   * Protobuf type {@code sync_pb.ExtensionSettingSpecifics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.components.sync.protocol.ExtensionSettingSpecifics, Builder> implements
      // @@protoc_insertion_point(builder_implements:sync_pb.ExtensionSettingSpecifics)
      org.chromium.components.sync.protocol.ExtensionSettingSpecificsOrBuilder {
    // Construct using org.chromium.components.sync.protocol.ExtensionSettingSpecifics.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Id of the extension the setting is for.
     * </pre>
     *
     * <code>optional string extension_id = 1;</code>
     */
    public boolean hasExtensionId() {
      return instance.hasExtensionId();
    }
    /**
     * <pre>
     * Id of the extension the setting is for.
     * </pre>
     *
     * <code>optional string extension_id = 1;</code>
     */
    public java.lang.String getExtensionId() {
      return instance.getExtensionId();
    }
    /**
     * <pre>
     * Id of the extension the setting is for.
     * </pre>
     *
     * <code>optional string extension_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getExtensionIdBytes() {
      return instance.getExtensionIdBytes();
    }
    /**
     * <pre>
     * Id of the extension the setting is for.
     * </pre>
     *
     * <code>optional string extension_id = 1;</code>
     */
    public Builder setExtensionId(
        java.lang.String value) {
      copyOnWrite();
      instance.setExtensionId(value);
      return this;
    }
    /**
     * <pre>
     * Id of the extension the setting is for.
     * </pre>
     *
     * <code>optional string extension_id = 1;</code>
     */
    public Builder clearExtensionId() {
      copyOnWrite();
      instance.clearExtensionId();
      return this;
    }
    /**
     * <pre>
     * Id of the extension the setting is for.
     * </pre>
     *
     * <code>optional string extension_id = 1;</code>
     */
    public Builder setExtensionIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setExtensionIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * Setting key.
     * </pre>
     *
     * <code>optional string key = 2;</code>
     */
    public boolean hasKey() {
      return instance.hasKey();
    }
    /**
     * <pre>
     * Setting key.
     * </pre>
     *
     * <code>optional string key = 2;</code>
     */
    public java.lang.String getKey() {
      return instance.getKey();
    }
    /**
     * <pre>
     * Setting key.
     * </pre>
     *
     * <code>optional string key = 2;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      return instance.getKeyBytes();
    }
    /**
     * <pre>
     * Setting key.
     * </pre>
     *
     * <code>optional string key = 2;</code>
     */
    public Builder setKey(
        java.lang.String value) {
      copyOnWrite();
      instance.setKey(value);
      return this;
    }
    /**
     * <pre>
     * Setting key.
     * </pre>
     *
     * <code>optional string key = 2;</code>
     */
    public Builder clearKey() {
      copyOnWrite();
      instance.clearKey();
      return this;
    }
    /**
     * <pre>
     * Setting key.
     * </pre>
     *
     * <code>optional string key = 2;</code>
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setKeyBytes(value);
      return this;
    }

    /**
     * <pre>
     * Setting value serialized as JSON.
     * </pre>
     *
     * <code>optional string value = 3;</code>
     */
    public boolean hasValue() {
      return instance.hasValue();
    }
    /**
     * <pre>
     * Setting value serialized as JSON.
     * </pre>
     *
     * <code>optional string value = 3;</code>
     */
    public java.lang.String getValue() {
      return instance.getValue();
    }
    /**
     * <pre>
     * Setting value serialized as JSON.
     * </pre>
     *
     * <code>optional string value = 3;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      return instance.getValueBytes();
    }
    /**
     * <pre>
     * Setting value serialized as JSON.
     * </pre>
     *
     * <code>optional string value = 3;</code>
     */
    public Builder setValue(
        java.lang.String value) {
      copyOnWrite();
      instance.setValue(value);
      return this;
    }
    /**
     * <pre>
     * Setting value serialized as JSON.
     * </pre>
     *
     * <code>optional string value = 3;</code>
     */
    public Builder clearValue() {
      copyOnWrite();
      instance.clearValue();
      return this;
    }
    /**
     * <pre>
     * Setting value serialized as JSON.
     * </pre>
     *
     * <code>optional string value = 3;</code>
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setValueBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sync_pb.ExtensionSettingSpecifics)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.components.sync.protocol.ExtensionSettingSpecifics();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        org.chromium.components.sync.protocol.ExtensionSettingSpecifics other = (org.chromium.components.sync.protocol.ExtensionSettingSpecifics) arg1;
        extensionId_ = visitor.visitString(
            hasExtensionId(), extensionId_,
            other.hasExtensionId(), other.extensionId_);
        key_ = visitor.visitString(
            hasKey(), key_,
            other.hasKey(), other.key_);
        value_ = visitor.visitString(
            hasValue(), value_,
            other.hasValue(), other.value_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readString();
                bitField0_ |= 0x00000001;
                extensionId_ = s;
                break;
              }
              case 18: {
                String s = input.readString();
                bitField0_ |= 0x00000002;
                key_ = s;
                break;
              }
              case 26: {
                String s = input.readString();
                bitField0_ |= 0x00000004;
                value_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (org.chromium.components.sync.protocol.ExtensionSettingSpecifics.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sync_pb.ExtensionSettingSpecifics)
  private static final org.chromium.components.sync.protocol.ExtensionSettingSpecifics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ExtensionSettingSpecifics();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static org.chromium.components.sync.protocol.ExtensionSettingSpecifics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ExtensionSettingSpecifics> PARSER;

  public static com.google.protobuf.Parser<ExtensionSettingSpecifics> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

