// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gaia_password_reuse.proto

package org.chromium.components.sync.protocol;

public interface GaiaPasswordReuseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sync_pb.GaiaPasswordReuse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .sync_pb.GaiaPasswordReuse.PasswordReuseDetected reuse_detected = 1;</code>
   */
  boolean hasReuseDetected();
  /**
   * <code>optional .sync_pb.GaiaPasswordReuse.PasswordReuseDetected reuse_detected = 1;</code>
   */
  org.chromium.components.sync.protocol.GaiaPasswordReuse.PasswordReuseDetected getReuseDetected();

  /**
   * <pre>
   * Logged when we try to detect whether the password was reused on a
   * Phishing or a Low-reputation site.
   * </pre>
   *
   * <code>optional .sync_pb.GaiaPasswordReuse.PasswordReuseLookup reuse_lookup = 2;</code>
   */
  boolean hasReuseLookup();
  /**
   * <pre>
   * Logged when we try to detect whether the password was reused on a
   * Phishing or a Low-reputation site.
   * </pre>
   *
   * <code>optional .sync_pb.GaiaPasswordReuse.PasswordReuseLookup reuse_lookup = 2;</code>
   */
  org.chromium.components.sync.protocol.GaiaPasswordReuse.PasswordReuseLookup getReuseLookup();

  /**
   * <code>optional .sync_pb.GaiaPasswordReuse.PasswordReuseDialogInteraction dialog_interaction = 3;</code>
   */
  boolean hasDialogInteraction();
  /**
   * <code>optional .sync_pb.GaiaPasswordReuse.PasswordReuseDialogInteraction dialog_interaction = 3;</code>
   */
  org.chromium.components.sync.protocol.GaiaPasswordReuse.PasswordReuseDialogInteraction getDialogInteraction();

  /**
   * <code>optional .sync_pb.GaiaPasswordReuse.PasswordCaptured password_captured = 4;</code>
   */
  boolean hasPasswordCaptured();
  /**
   * <code>optional .sync_pb.GaiaPasswordReuse.PasswordCaptured password_captured = 4;</code>
   */
  org.chromium.components.sync.protocol.GaiaPasswordReuse.PasswordCaptured getPasswordCaptured();
}
