// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app_specifics.proto

package org.chromium.components.sync.protocol;

/**
 * <pre>
 * Information about a linked app icon.
 * </pre>
 *
 * Protobuf type {@code sync_pb.LinkedAppIconInfo}
 */
public  final class LinkedAppIconInfo extends
    com.google.protobuf.GeneratedMessageLite<
        LinkedAppIconInfo, LinkedAppIconInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:sync_pb.LinkedAppIconInfo)
    LinkedAppIconInfoOrBuilder {
  private LinkedAppIconInfo() {
    url_ = "";
  }
  private int bitField0_;
  public static final int URL_FIELD_NUMBER = 1;
  private java.lang.String url_;
  /**
   * <pre>
   * The URL of the app icon.
   * </pre>
   *
   * <code>optional string url = 1;</code>
   */
  public boolean hasUrl() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * The URL of the app icon.
   * </pre>
   *
   * <code>optional string url = 1;</code>
   */
  public java.lang.String getUrl() {
    return url_;
  }
  /**
   * <pre>
   * The URL of the app icon.
   * </pre>
   *
   * <code>optional string url = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(url_);
  }
  /**
   * <pre>
   * The URL of the app icon.
   * </pre>
   *
   * <code>optional string url = 1;</code>
   */
  private void setUrl(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    url_ = value;
  }
  /**
   * <pre>
   * The URL of the app icon.
   * </pre>
   *
   * <code>optional string url = 1;</code>
   */
  private void clearUrl() {
    bitField0_ = (bitField0_ & ~0x00000001);
    url_ = getDefaultInstance().getUrl();
  }
  /**
   * <pre>
   * The URL of the app icon.
   * </pre>
   *
   * <code>optional string url = 1;</code>
   */
  private void setUrlBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    url_ = value.toStringUtf8();
  }

  public static final int SIZE_FIELD_NUMBER = 2;
  private int size_;
  /**
   * <pre>
   * The size of the app icon in DIPs.
   * </pre>
   *
   * <code>optional uint32 size = 2;</code>
   */
  public boolean hasSize() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <pre>
   * The size of the app icon in DIPs.
   * </pre>
   *
   * <code>optional uint32 size = 2;</code>
   */
  public int getSize() {
    return size_;
  }
  /**
   * <pre>
   * The size of the app icon in DIPs.
   * </pre>
   *
   * <code>optional uint32 size = 2;</code>
   */
  private void setSize(int value) {
    bitField0_ |= 0x00000002;
    size_ = value;
  }
  /**
   * <pre>
   * The size of the app icon in DIPs.
   * </pre>
   *
   * <code>optional uint32 size = 2;</code>
   */
  private void clearSize() {
    bitField0_ = (bitField0_ & ~0x00000002);
    size_ = 0;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeString(1, getUrl());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeUInt32(2, size_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getUrl());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, size_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static org.chromium.components.sync.protocol.LinkedAppIconInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.LinkedAppIconInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.LinkedAppIconInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.LinkedAppIconInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.LinkedAppIconInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.LinkedAppIconInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.LinkedAppIconInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.LinkedAppIconInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.LinkedAppIconInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.LinkedAppIconInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.chromium.components.sync.protocol.LinkedAppIconInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * Information about a linked app icon.
   * </pre>
   *
   * Protobuf type {@code sync_pb.LinkedAppIconInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.components.sync.protocol.LinkedAppIconInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:sync_pb.LinkedAppIconInfo)
      org.chromium.components.sync.protocol.LinkedAppIconInfoOrBuilder {
    // Construct using org.chromium.components.sync.protocol.LinkedAppIconInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The URL of the app icon.
     * </pre>
     *
     * <code>optional string url = 1;</code>
     */
    public boolean hasUrl() {
      return instance.hasUrl();
    }
    /**
     * <pre>
     * The URL of the app icon.
     * </pre>
     *
     * <code>optional string url = 1;</code>
     */
    public java.lang.String getUrl() {
      return instance.getUrl();
    }
    /**
     * <pre>
     * The URL of the app icon.
     * </pre>
     *
     * <code>optional string url = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      return instance.getUrlBytes();
    }
    /**
     * <pre>
     * The URL of the app icon.
     * </pre>
     *
     * <code>optional string url = 1;</code>
     */
    public Builder setUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setUrl(value);
      return this;
    }
    /**
     * <pre>
     * The URL of the app icon.
     * </pre>
     *
     * <code>optional string url = 1;</code>
     */
    public Builder clearUrl() {
      copyOnWrite();
      instance.clearUrl();
      return this;
    }
    /**
     * <pre>
     * The URL of the app icon.
     * </pre>
     *
     * <code>optional string url = 1;</code>
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUrlBytes(value);
      return this;
    }

    /**
     * <pre>
     * The size of the app icon in DIPs.
     * </pre>
     *
     * <code>optional uint32 size = 2;</code>
     */
    public boolean hasSize() {
      return instance.hasSize();
    }
    /**
     * <pre>
     * The size of the app icon in DIPs.
     * </pre>
     *
     * <code>optional uint32 size = 2;</code>
     */
    public int getSize() {
      return instance.getSize();
    }
    /**
     * <pre>
     * The size of the app icon in DIPs.
     * </pre>
     *
     * <code>optional uint32 size = 2;</code>
     */
    public Builder setSize(int value) {
      copyOnWrite();
      instance.setSize(value);
      return this;
    }
    /**
     * <pre>
     * The size of the app icon in DIPs.
     * </pre>
     *
     * <code>optional uint32 size = 2;</code>
     */
    public Builder clearSize() {
      copyOnWrite();
      instance.clearSize();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sync_pb.LinkedAppIconInfo)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.components.sync.protocol.LinkedAppIconInfo();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        org.chromium.components.sync.protocol.LinkedAppIconInfo other = (org.chromium.components.sync.protocol.LinkedAppIconInfo) arg1;
        url_ = visitor.visitString(
            hasUrl(), url_,
            other.hasUrl(), other.url_);
        size_ = visitor.visitInt(
            hasSize(), size_,
            other.hasSize(), other.size_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readString();
                bitField0_ |= 0x00000001;
                url_ = s;
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                size_ = input.readUInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (org.chromium.components.sync.protocol.LinkedAppIconInfo.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sync_pb.LinkedAppIconInfo)
  private static final org.chromium.components.sync.protocol.LinkedAppIconInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new LinkedAppIconInfo();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static org.chromium.components.sync.protocol.LinkedAppIconInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<LinkedAppIconInfo> PARSER;

  public static com.google.protobuf.Parser<LinkedAppIconInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

