// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: managed_user_shared_setting_specifics.proto

package org.chromium.components.sync.protocol;

public final class ManagedUserSharedSettingSpecificsOuterClass {
  private ManagedUserSharedSettingSpecificsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
