// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: managed_user_whitelist_specifics.proto

package org.chromium.components.sync.protocol;

public interface ManagedUserWhitelistSpecificsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sync_pb.ManagedUserWhitelistSpecifics)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Globally unique id for this whitelist that identifies it in the Web Store.
   * </pre>
   *
   * <code>optional string id = 1;</code>
   */
  boolean hasId();
  /**
   * <pre>
   * Globally unique id for this whitelist that identifies it in the Web Store.
   * </pre>
   *
   * <code>optional string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   * Globally unique id for this whitelist that identifies it in the Web Store.
   * </pre>
   *
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * The name of the whitelist.
   * </pre>
   *
   * <code>optional string name = 2;</code>
   */
  boolean hasName();
  /**
   * <pre>
   * The name of the whitelist.
   * </pre>
   *
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * The name of the whitelist.
   * </pre>
   *
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
