// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: os_preference_specifics.proto

package org.chromium.components.sync.protocol;

public interface OsPreferenceSpecificsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sync_pb.OsPreferenceSpecifics)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .sync_pb.PreferenceSpecifics preference = 1;</code>
   */
  boolean hasPreference();
  /**
   * <code>optional .sync_pb.PreferenceSpecifics preference = 1;</code>
   */
  org.chromium.components.sync.protocol.PreferenceSpecifics getPreference();
}
