// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sync.proto

package org.chromium.components.sync.protocol;

/**
 * <pre>
 * Used for inspecting how long we spent performing operations in different
 * backends. All times must be in millis.
 * </pre>
 *
 * Protobuf type {@code sync_pb.ProfilingData}
 */
public  final class ProfilingData extends
    com.google.protobuf.GeneratedMessageLite<
        ProfilingData, ProfilingData.Builder> implements
    // @@protoc_insertion_point(message_implements:sync_pb.ProfilingData)
    ProfilingDataOrBuilder {
  private ProfilingData() {
  }
  private int bitField0_;
  public static final int META_DATA_WRITE_TIME_FIELD_NUMBER = 1;
  private long metaDataWriteTime_;
  /**
   * <code>optional int64 meta_data_write_time = 1;</code>
   */
  public boolean hasMetaDataWriteTime() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional int64 meta_data_write_time = 1;</code>
   */
  public long getMetaDataWriteTime() {
    return metaDataWriteTime_;
  }
  /**
   * <code>optional int64 meta_data_write_time = 1;</code>
   */
  private void setMetaDataWriteTime(long value) {
    bitField0_ |= 0x00000001;
    metaDataWriteTime_ = value;
  }
  /**
   * <code>optional int64 meta_data_write_time = 1;</code>
   */
  private void clearMetaDataWriteTime() {
    bitField0_ = (bitField0_ & ~0x00000001);
    metaDataWriteTime_ = 0L;
  }

  public static final int FILE_DATA_WRITE_TIME_FIELD_NUMBER = 2;
  private long fileDataWriteTime_;
  /**
   * <code>optional int64 file_data_write_time = 2;</code>
   */
  public boolean hasFileDataWriteTime() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional int64 file_data_write_time = 2;</code>
   */
  public long getFileDataWriteTime() {
    return fileDataWriteTime_;
  }
  /**
   * <code>optional int64 file_data_write_time = 2;</code>
   */
  private void setFileDataWriteTime(long value) {
    bitField0_ |= 0x00000002;
    fileDataWriteTime_ = value;
  }
  /**
   * <code>optional int64 file_data_write_time = 2;</code>
   */
  private void clearFileDataWriteTime() {
    bitField0_ = (bitField0_ & ~0x00000002);
    fileDataWriteTime_ = 0L;
  }

  public static final int USER_LOOKUP_TIME_FIELD_NUMBER = 3;
  private long userLookupTime_;
  /**
   * <code>optional int64 user_lookup_time = 3;</code>
   */
  public boolean hasUserLookupTime() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional int64 user_lookup_time = 3;</code>
   */
  public long getUserLookupTime() {
    return userLookupTime_;
  }
  /**
   * <code>optional int64 user_lookup_time = 3;</code>
   */
  private void setUserLookupTime(long value) {
    bitField0_ |= 0x00000004;
    userLookupTime_ = value;
  }
  /**
   * <code>optional int64 user_lookup_time = 3;</code>
   */
  private void clearUserLookupTime() {
    bitField0_ = (bitField0_ & ~0x00000004);
    userLookupTime_ = 0L;
  }

  public static final int META_DATA_READ_TIME_FIELD_NUMBER = 4;
  private long metaDataReadTime_;
  /**
   * <code>optional int64 meta_data_read_time = 4;</code>
   */
  public boolean hasMetaDataReadTime() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional int64 meta_data_read_time = 4;</code>
   */
  public long getMetaDataReadTime() {
    return metaDataReadTime_;
  }
  /**
   * <code>optional int64 meta_data_read_time = 4;</code>
   */
  private void setMetaDataReadTime(long value) {
    bitField0_ |= 0x00000008;
    metaDataReadTime_ = value;
  }
  /**
   * <code>optional int64 meta_data_read_time = 4;</code>
   */
  private void clearMetaDataReadTime() {
    bitField0_ = (bitField0_ & ~0x00000008);
    metaDataReadTime_ = 0L;
  }

  public static final int FILE_DATA_READ_TIME_FIELD_NUMBER = 5;
  private long fileDataReadTime_;
  /**
   * <code>optional int64 file_data_read_time = 5;</code>
   */
  public boolean hasFileDataReadTime() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional int64 file_data_read_time = 5;</code>
   */
  public long getFileDataReadTime() {
    return fileDataReadTime_;
  }
  /**
   * <code>optional int64 file_data_read_time = 5;</code>
   */
  private void setFileDataReadTime(long value) {
    bitField0_ |= 0x00000010;
    fileDataReadTime_ = value;
  }
  /**
   * <code>optional int64 file_data_read_time = 5;</code>
   */
  private void clearFileDataReadTime() {
    bitField0_ = (bitField0_ & ~0x00000010);
    fileDataReadTime_ = 0L;
  }

  public static final int TOTAL_REQUEST_TIME_FIELD_NUMBER = 6;
  private long totalRequestTime_;
  /**
   * <code>optional int64 total_request_time = 6;</code>
   */
  public boolean hasTotalRequestTime() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional int64 total_request_time = 6;</code>
   */
  public long getTotalRequestTime() {
    return totalRequestTime_;
  }
  /**
   * <code>optional int64 total_request_time = 6;</code>
   */
  private void setTotalRequestTime(long value) {
    bitField0_ |= 0x00000020;
    totalRequestTime_ = value;
  }
  /**
   * <code>optional int64 total_request_time = 6;</code>
   */
  private void clearTotalRequestTime() {
    bitField0_ = (bitField0_ & ~0x00000020);
    totalRequestTime_ = 0L;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt64(1, metaDataWriteTime_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt64(2, fileDataWriteTime_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt64(3, userLookupTime_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt64(4, metaDataReadTime_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeInt64(5, fileDataReadTime_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeInt64(6, totalRequestTime_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, metaDataWriteTime_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, fileDataWriteTime_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, userLookupTime_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, metaDataReadTime_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, fileDataReadTime_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, totalRequestTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static org.chromium.components.sync.protocol.ProfilingData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.ProfilingData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ProfilingData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.ProfilingData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ProfilingData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.ProfilingData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ProfilingData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.ProfilingData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.ProfilingData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.ProfilingData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.chromium.components.sync.protocol.ProfilingData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * Used for inspecting how long we spent performing operations in different
   * backends. All times must be in millis.
   * </pre>
   *
   * Protobuf type {@code sync_pb.ProfilingData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.components.sync.protocol.ProfilingData, Builder> implements
      // @@protoc_insertion_point(builder_implements:sync_pb.ProfilingData)
      org.chromium.components.sync.protocol.ProfilingDataOrBuilder {
    // Construct using org.chromium.components.sync.protocol.ProfilingData.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional int64 meta_data_write_time = 1;</code>
     */
    public boolean hasMetaDataWriteTime() {
      return instance.hasMetaDataWriteTime();
    }
    /**
     * <code>optional int64 meta_data_write_time = 1;</code>
     */
    public long getMetaDataWriteTime() {
      return instance.getMetaDataWriteTime();
    }
    /**
     * <code>optional int64 meta_data_write_time = 1;</code>
     */
    public Builder setMetaDataWriteTime(long value) {
      copyOnWrite();
      instance.setMetaDataWriteTime(value);
      return this;
    }
    /**
     * <code>optional int64 meta_data_write_time = 1;</code>
     */
    public Builder clearMetaDataWriteTime() {
      copyOnWrite();
      instance.clearMetaDataWriteTime();
      return this;
    }

    /**
     * <code>optional int64 file_data_write_time = 2;</code>
     */
    public boolean hasFileDataWriteTime() {
      return instance.hasFileDataWriteTime();
    }
    /**
     * <code>optional int64 file_data_write_time = 2;</code>
     */
    public long getFileDataWriteTime() {
      return instance.getFileDataWriteTime();
    }
    /**
     * <code>optional int64 file_data_write_time = 2;</code>
     */
    public Builder setFileDataWriteTime(long value) {
      copyOnWrite();
      instance.setFileDataWriteTime(value);
      return this;
    }
    /**
     * <code>optional int64 file_data_write_time = 2;</code>
     */
    public Builder clearFileDataWriteTime() {
      copyOnWrite();
      instance.clearFileDataWriteTime();
      return this;
    }

    /**
     * <code>optional int64 user_lookup_time = 3;</code>
     */
    public boolean hasUserLookupTime() {
      return instance.hasUserLookupTime();
    }
    /**
     * <code>optional int64 user_lookup_time = 3;</code>
     */
    public long getUserLookupTime() {
      return instance.getUserLookupTime();
    }
    /**
     * <code>optional int64 user_lookup_time = 3;</code>
     */
    public Builder setUserLookupTime(long value) {
      copyOnWrite();
      instance.setUserLookupTime(value);
      return this;
    }
    /**
     * <code>optional int64 user_lookup_time = 3;</code>
     */
    public Builder clearUserLookupTime() {
      copyOnWrite();
      instance.clearUserLookupTime();
      return this;
    }

    /**
     * <code>optional int64 meta_data_read_time = 4;</code>
     */
    public boolean hasMetaDataReadTime() {
      return instance.hasMetaDataReadTime();
    }
    /**
     * <code>optional int64 meta_data_read_time = 4;</code>
     */
    public long getMetaDataReadTime() {
      return instance.getMetaDataReadTime();
    }
    /**
     * <code>optional int64 meta_data_read_time = 4;</code>
     */
    public Builder setMetaDataReadTime(long value) {
      copyOnWrite();
      instance.setMetaDataReadTime(value);
      return this;
    }
    /**
     * <code>optional int64 meta_data_read_time = 4;</code>
     */
    public Builder clearMetaDataReadTime() {
      copyOnWrite();
      instance.clearMetaDataReadTime();
      return this;
    }

    /**
     * <code>optional int64 file_data_read_time = 5;</code>
     */
    public boolean hasFileDataReadTime() {
      return instance.hasFileDataReadTime();
    }
    /**
     * <code>optional int64 file_data_read_time = 5;</code>
     */
    public long getFileDataReadTime() {
      return instance.getFileDataReadTime();
    }
    /**
     * <code>optional int64 file_data_read_time = 5;</code>
     */
    public Builder setFileDataReadTime(long value) {
      copyOnWrite();
      instance.setFileDataReadTime(value);
      return this;
    }
    /**
     * <code>optional int64 file_data_read_time = 5;</code>
     */
    public Builder clearFileDataReadTime() {
      copyOnWrite();
      instance.clearFileDataReadTime();
      return this;
    }

    /**
     * <code>optional int64 total_request_time = 6;</code>
     */
    public boolean hasTotalRequestTime() {
      return instance.hasTotalRequestTime();
    }
    /**
     * <code>optional int64 total_request_time = 6;</code>
     */
    public long getTotalRequestTime() {
      return instance.getTotalRequestTime();
    }
    /**
     * <code>optional int64 total_request_time = 6;</code>
     */
    public Builder setTotalRequestTime(long value) {
      copyOnWrite();
      instance.setTotalRequestTime(value);
      return this;
    }
    /**
     * <code>optional int64 total_request_time = 6;</code>
     */
    public Builder clearTotalRequestTime() {
      copyOnWrite();
      instance.clearTotalRequestTime();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sync_pb.ProfilingData)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.components.sync.protocol.ProfilingData();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        org.chromium.components.sync.protocol.ProfilingData other = (org.chromium.components.sync.protocol.ProfilingData) arg1;
        metaDataWriteTime_ = visitor.visitLong(
            hasMetaDataWriteTime(), metaDataWriteTime_,
            other.hasMetaDataWriteTime(), other.metaDataWriteTime_);
        fileDataWriteTime_ = visitor.visitLong(
            hasFileDataWriteTime(), fileDataWriteTime_,
            other.hasFileDataWriteTime(), other.fileDataWriteTime_);
        userLookupTime_ = visitor.visitLong(
            hasUserLookupTime(), userLookupTime_,
            other.hasUserLookupTime(), other.userLookupTime_);
        metaDataReadTime_ = visitor.visitLong(
            hasMetaDataReadTime(), metaDataReadTime_,
            other.hasMetaDataReadTime(), other.metaDataReadTime_);
        fileDataReadTime_ = visitor.visitLong(
            hasFileDataReadTime(), fileDataReadTime_,
            other.hasFileDataReadTime(), other.fileDataReadTime_);
        totalRequestTime_ = visitor.visitLong(
            hasTotalRequestTime(), totalRequestTime_,
            other.hasTotalRequestTime(), other.totalRequestTime_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                metaDataWriteTime_ = input.readInt64();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                fileDataWriteTime_ = input.readInt64();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                userLookupTime_ = input.readInt64();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                metaDataReadTime_ = input.readInt64();
                break;
              }
              case 40: {
                bitField0_ |= 0x00000010;
                fileDataReadTime_ = input.readInt64();
                break;
              }
              case 48: {
                bitField0_ |= 0x00000020;
                totalRequestTime_ = input.readInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (org.chromium.components.sync.protocol.ProfilingData.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sync_pb.ProfilingData)
  private static final org.chromium.components.sync.protocol.ProfilingData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ProfilingData();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static org.chromium.components.sync.protocol.ProfilingData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ProfilingData> PARSER;

  public static com.google.protobuf.Parser<ProfilingData> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

