// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: session_specifics.proto

package org.chromium.components.sync.protocol;

public interface SessionSpecificsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sync_pb.SessionSpecifics)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Unique id for the client.
   * </pre>
   *
   * <code>optional string session_tag = 1;</code>
   */
  boolean hasSessionTag();
  /**
   * <pre>
   * Unique id for the client.
   * </pre>
   *
   * <code>optional string session_tag = 1;</code>
   */
  java.lang.String getSessionTag();
  /**
   * <pre>
   * Unique id for the client.
   * </pre>
   *
   * <code>optional string session_tag = 1;</code>
   */
  com.google.protobuf.ByteString
      getSessionTagBytes();

  /**
   * <code>optional .sync_pb.SessionHeader header = 2;</code>
   */
  boolean hasHeader();
  /**
   * <code>optional .sync_pb.SessionHeader header = 2;</code>
   */
  org.chromium.components.sync.protocol.SessionHeader getHeader();

  /**
   * <code>optional .sync_pb.SessionTab tab = 3;</code>
   */
  boolean hasTab();
  /**
   * <code>optional .sync_pb.SessionTab tab = 3;</code>
   */
  org.chromium.components.sync.protocol.SessionTab getTab();

  /**
   * <pre>
   * The local tab id used by sync. Unique across all nodes for that client.
   * </pre>
   *
   * <code>optional int32 tab_node_id = 4 [default = -1];</code>
   */
  boolean hasTabNodeId();
  /**
   * <pre>
   * The local tab id used by sync. Unique across all nodes for that client.
   * </pre>
   *
   * <code>optional int32 tab_node_id = 4 [default = -1];</code>
   */
  int getTabNodeId();
}
