// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_debug_info.proto

package org.chromium.components.sync.protocol;

/**
 * <pre>
 * Per-type hint information.
 * </pre>
 *
 * Protobuf type {@code sync_pb.TypeHint}
 */
public  final class TypeHint extends
    com.google.protobuf.GeneratedMessageLite<
        TypeHint, TypeHint.Builder> implements
    // @@protoc_insertion_point(message_implements:sync_pb.TypeHint)
    TypeHintOrBuilder {
  private TypeHint() {
  }
  private int bitField0_;
  public static final int DATA_TYPE_ID_FIELD_NUMBER = 1;
  private int dataTypeId_;
  /**
   * <pre>
   * The data type this hint applied to.
   * </pre>
   *
   * <code>optional int32 data_type_id = 1;</code>
   */
  public boolean hasDataTypeId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * The data type this hint applied to.
   * </pre>
   *
   * <code>optional int32 data_type_id = 1;</code>
   */
  public int getDataTypeId() {
    return dataTypeId_;
  }
  /**
   * <pre>
   * The data type this hint applied to.
   * </pre>
   *
   * <code>optional int32 data_type_id = 1;</code>
   */
  private void setDataTypeId(int value) {
    bitField0_ |= 0x00000001;
    dataTypeId_ = value;
  }
  /**
   * <pre>
   * The data type this hint applied to.
   * </pre>
   *
   * <code>optional int32 data_type_id = 1;</code>
   */
  private void clearDataTypeId() {
    bitField0_ = (bitField0_ & ~0x00000001);
    dataTypeId_ = 0;
  }

  public static final int HAS_VALID_HINT_FIELD_NUMBER = 2;
  private boolean hasValidHint_;
  /**
   * <pre>
   * Whether or not a valid hint is provided.
   * </pre>
   *
   * <code>optional bool has_valid_hint = 2;</code>
   */
  public boolean hasHasValidHint() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <pre>
   * Whether or not a valid hint is provided.
   * </pre>
   *
   * <code>optional bool has_valid_hint = 2;</code>
   */
  public boolean getHasValidHint() {
    return hasValidHint_;
  }
  /**
   * <pre>
   * Whether or not a valid hint is provided.
   * </pre>
   *
   * <code>optional bool has_valid_hint = 2;</code>
   */
  private void setHasValidHint(boolean value) {
    bitField0_ |= 0x00000002;
    hasValidHint_ = value;
  }
  /**
   * <pre>
   * Whether or not a valid hint is provided.
   * </pre>
   *
   * <code>optional bool has_valid_hint = 2;</code>
   */
  private void clearHasValidHint() {
    bitField0_ = (bitField0_ & ~0x00000002);
    hasValidHint_ = false;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, dataTypeId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBool(2, hasValidHint_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, dataTypeId_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, hasValidHint_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static org.chromium.components.sync.protocol.TypeHint parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.TypeHint parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.TypeHint parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.TypeHint parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.TypeHint parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.TypeHint parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.TypeHint parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.TypeHint parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.TypeHint parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.TypeHint parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.chromium.components.sync.protocol.TypeHint prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * Per-type hint information.
   * </pre>
   *
   * Protobuf type {@code sync_pb.TypeHint}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.components.sync.protocol.TypeHint, Builder> implements
      // @@protoc_insertion_point(builder_implements:sync_pb.TypeHint)
      org.chromium.components.sync.protocol.TypeHintOrBuilder {
    // Construct using org.chromium.components.sync.protocol.TypeHint.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The data type this hint applied to.
     * </pre>
     *
     * <code>optional int32 data_type_id = 1;</code>
     */
    public boolean hasDataTypeId() {
      return instance.hasDataTypeId();
    }
    /**
     * <pre>
     * The data type this hint applied to.
     * </pre>
     *
     * <code>optional int32 data_type_id = 1;</code>
     */
    public int getDataTypeId() {
      return instance.getDataTypeId();
    }
    /**
     * <pre>
     * The data type this hint applied to.
     * </pre>
     *
     * <code>optional int32 data_type_id = 1;</code>
     */
    public Builder setDataTypeId(int value) {
      copyOnWrite();
      instance.setDataTypeId(value);
      return this;
    }
    /**
     * <pre>
     * The data type this hint applied to.
     * </pre>
     *
     * <code>optional int32 data_type_id = 1;</code>
     */
    public Builder clearDataTypeId() {
      copyOnWrite();
      instance.clearDataTypeId();
      return this;
    }

    /**
     * <pre>
     * Whether or not a valid hint is provided.
     * </pre>
     *
     * <code>optional bool has_valid_hint = 2;</code>
     */
    public boolean hasHasValidHint() {
      return instance.hasHasValidHint();
    }
    /**
     * <pre>
     * Whether or not a valid hint is provided.
     * </pre>
     *
     * <code>optional bool has_valid_hint = 2;</code>
     */
    public boolean getHasValidHint() {
      return instance.getHasValidHint();
    }
    /**
     * <pre>
     * Whether or not a valid hint is provided.
     * </pre>
     *
     * <code>optional bool has_valid_hint = 2;</code>
     */
    public Builder setHasValidHint(boolean value) {
      copyOnWrite();
      instance.setHasValidHint(value);
      return this;
    }
    /**
     * <pre>
     * Whether or not a valid hint is provided.
     * </pre>
     *
     * <code>optional bool has_valid_hint = 2;</code>
     */
    public Builder clearHasValidHint() {
      copyOnWrite();
      instance.clearHasValidHint();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sync_pb.TypeHint)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.components.sync.protocol.TypeHint();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        org.chromium.components.sync.protocol.TypeHint other = (org.chromium.components.sync.protocol.TypeHint) arg1;
        dataTypeId_ = visitor.visitInt(
            hasDataTypeId(), dataTypeId_,
            other.hasDataTypeId(), other.dataTypeId_);
        hasValidHint_ = visitor.visitBoolean(
            hasHasValidHint(), hasValidHint_,
            other.hasHasValidHint(), other.hasValidHint_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                dataTypeId_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                hasValidHint_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (org.chromium.components.sync.protocol.TypeHint.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sync_pb.TypeHint)
  private static final org.chromium.components.sync.protocol.TypeHint DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TypeHint();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static org.chromium.components.sync.protocol.TypeHint getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<TypeHint> PARSER;

  public static com.google.protobuf.Parser<TypeHint> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

