// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: history_delete_directive_specifics.proto

package org.chromium.components.sync.protocol;

public interface UrlDirectiveOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sync_pb.UrlDirective)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * The URL that should be removed from history.
   * </pre>
   *
   * <code>optional string url = 1;</code>
   */
  boolean hasUrl();
  /**
   * <pre>
   * The URL that should be removed from history.
   * </pre>
   *
   * <code>optional string url = 1;</code>
   */
  java.lang.String getUrl();
  /**
   * <pre>
   * The URL that should be removed from history.
   * </pre>
   *
   * <code>optional string url = 1;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   * The time on or before which entries must be deleted.
   * In microseconds since the Unix epoch.
   * </pre>
   *
   * <code>optional int64 end_time_usec = 2;</code>
   */
  boolean hasEndTimeUsec();
  /**
   * <pre>
   * The time on or before which entries must be deleted.
   * In microseconds since the Unix epoch.
   * </pre>
   *
   * <code>optional int64 end_time_usec = 2;</code>
   */
  long getEndTimeUsec();
}
