// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: autofill_specifics.proto

package org.chromium.components.sync.protocol;

public interface WalletPostalAddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sync_pb.WalletPostalAddress)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>optional string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string recipient_name = 12;</code>
   */
  boolean hasRecipientName();
  /**
   * <code>optional string recipient_name = 12;</code>
   */
  java.lang.String getRecipientName();
  /**
   * <code>optional string recipient_name = 12;</code>
   */
  com.google.protobuf.ByteString
      getRecipientNameBytes();

  /**
   * <code>optional string company_name = 2;</code>
   */
  boolean hasCompanyName();
  /**
   * <code>optional string company_name = 2;</code>
   */
  java.lang.String getCompanyName();
  /**
   * <code>optional string company_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <pre>
   * This is the street address, of which there may be multiple lines. This
   * corresponds to "address_home_line[1|2] in the AutofillProfileSpecifics
   * message above. In some locales there may be more than two lines.
   * </pre>
   *
   * <code>repeated string street_address = 3;</code>
   */
  java.util.List<String>
      getStreetAddressList();
  /**
   * <pre>
   * This is the street address, of which there may be multiple lines. This
   * corresponds to "address_home_line[1|2] in the AutofillProfileSpecifics
   * message above. In some locales there may be more than two lines.
   * </pre>
   *
   * <code>repeated string street_address = 3;</code>
   */
  int getStreetAddressCount();
  /**
   * <pre>
   * This is the street address, of which there may be multiple lines. This
   * corresponds to "address_home_line[1|2] in the AutofillProfileSpecifics
   * message above. In some locales there may be more than two lines.
   * </pre>
   *
   * <code>repeated string street_address = 3;</code>
   */
  java.lang.String getStreetAddress(int index);
  /**
   * <pre>
   * This is the street address, of which there may be multiple lines. This
   * corresponds to "address_home_line[1|2] in the AutofillProfileSpecifics
   * message above. In some locales there may be more than two lines.
   * </pre>
   *
   * <code>repeated string street_address = 3;</code>
   */
  com.google.protobuf.ByteString
      getStreetAddressBytes(int index);

  /**
   * <pre>
   * Also known as "administrative area". This is normally the state or
   * province in most countries.
   * </pre>
   *
   * <code>optional string address_1 = 4;</code>
   */
  boolean hasAddress1();
  /**
   * <pre>
   * Also known as "administrative area". This is normally the state or
   * province in most countries.
   * </pre>
   *
   * <code>optional string address_1 = 4;</code>
   */
  java.lang.String getAddress1();
  /**
   * <pre>
   * Also known as "administrative area". This is normally the state or
   * province in most countries.
   * </pre>
   *
   * <code>optional string address_1 = 4;</code>
   */
  com.google.protobuf.ByteString
      getAddress1Bytes();

  /**
   * <pre>
   * Also known as "locality". In the US this is the city.
   * </pre>
   *
   * <code>optional string address_2 = 5;</code>
   */
  boolean hasAddress2();
  /**
   * <pre>
   * Also known as "locality". In the US this is the city.
   * </pre>
   *
   * <code>optional string address_2 = 5;</code>
   */
  java.lang.String getAddress2();
  /**
   * <pre>
   * Also known as "locality". In the US this is the city.
   * </pre>
   *
   * <code>optional string address_2 = 5;</code>
   */
  com.google.protobuf.ByteString
      getAddress2Bytes();

  /**
   * <pre>
   * A sub-classification beneath the city, e.g. an inner-city district or
   * suburb. Also known as "dependent_locality"
   * </pre>
   *
   * <code>optional string address_3 = 6;</code>
   */
  boolean hasAddress3();
  /**
   * <pre>
   * A sub-classification beneath the city, e.g. an inner-city district or
   * suburb. Also known as "dependent_locality"
   * </pre>
   *
   * <code>optional string address_3 = 6;</code>
   */
  java.lang.String getAddress3();
  /**
   * <pre>
   * A sub-classification beneath the city, e.g. an inner-city district or
   * suburb. Also known as "dependent_locality"
   * </pre>
   *
   * <code>optional string address_3 = 6;</code>
   */
  com.google.protobuf.ByteString
      getAddress3Bytes();

  /**
   * <pre>
   * Used in certain countries. Also known as "sub_dependent_locality".
   * </pre>
   *
   * <code>optional string address_4 = 7;</code>
   */
  boolean hasAddress4();
  /**
   * <pre>
   * Used in certain countries. Also known as "sub_dependent_locality".
   * </pre>
   *
   * <code>optional string address_4 = 7;</code>
   */
  java.lang.String getAddress4();
  /**
   * <pre>
   * Used in certain countries. Also known as "sub_dependent_locality".
   * </pre>
   *
   * <code>optional string address_4 = 7;</code>
   */
  com.google.protobuf.ByteString
      getAddress4Bytes();

  /**
   * <code>optional string postal_code = 8;</code>
   */
  boolean hasPostalCode();
  /**
   * <code>optional string postal_code = 8;</code>
   */
  java.lang.String getPostalCode();
  /**
   * <code>optional string postal_code = 8;</code>
   */
  com.google.protobuf.ByteString
      getPostalCodeBytes();

  /**
   * <pre>
   * Similar to the zipcode column, but used for businesses or organizations
   * that might not be geographically contiguous. The canonical example is
   * CEDEX in France.
   * </pre>
   *
   * <code>optional string sorting_code = 9;</code>
   */
  boolean hasSortingCode();
  /**
   * <pre>
   * Similar to the zipcode column, but used for businesses or organizations
   * that might not be geographically contiguous. The canonical example is
   * CEDEX in France.
   * </pre>
   *
   * <code>optional string sorting_code = 9;</code>
   */
  java.lang.String getSortingCode();
  /**
   * <pre>
   * Similar to the zipcode column, but used for businesses or organizations
   * that might not be geographically contiguous. The canonical example is
   * CEDEX in France.
   * </pre>
   *
   * <code>optional string sorting_code = 9;</code>
   */
  com.google.protobuf.ByteString
      getSortingCodeBytes();

  /**
   * <code>optional string country_code = 10;</code>
   */
  boolean hasCountryCode();
  /**
   * <code>optional string country_code = 10;</code>
   */
  java.lang.String getCountryCode();
  /**
   * <code>optional string country_code = 10;</code>
   */
  com.google.protobuf.ByteString
      getCountryCodeBytes();

  /**
   * <code>optional string language_code = 11;</code>
   */
  boolean hasLanguageCode();
  /**
   * <code>optional string language_code = 11;</code>
   */
  java.lang.String getLanguageCode();
  /**
   * <code>optional string language_code = 11;</code>
   */
  com.google.protobuf.ByteString
      getLanguageCodeBytes();

  /**
   * <pre>
   * Phone number. The format is unspecified and will be explicitly ignored.
   * </pre>
   *
   * <code>optional string phone_number = 13;</code>
   */
  boolean hasPhoneNumber();
  /**
   * <pre>
   * Phone number. The format is unspecified and will be explicitly ignored.
   * </pre>
   *
   * <code>optional string phone_number = 13;</code>
   */
  java.lang.String getPhoneNumber();
  /**
   * <pre>
   * Phone number. The format is unspecified and will be explicitly ignored.
   * </pre>
   *
   * <code>optional string phone_number = 13;</code>
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();
}
