// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: autofill_specifics.proto

package org.chromium.components.sync.protocol;

/**
 * Protobuf type {@code sync_pb.WalletMaskedCreditCard}
 */
public  final class WalletMaskedCreditCard extends
    com.google.protobuf.GeneratedMessageLite<
        WalletMaskedCreditCard, WalletMaskedCreditCard.Builder> implements
    // @@protoc_insertion_point(message_implements:sync_pb.WalletMaskedCreditCard)
    WalletMaskedCreditCardOrBuilder {
  private WalletMaskedCreditCard() {
    id_ = "";
    nameOnCard_ = "";
    lastFour_ = "";
    billingAddressId_ = "";
    bankName_ = "";
  }
  /**
   * Protobuf enum {@code sync_pb.WalletMaskedCreditCard.WalletCardStatus}
   */
  public enum WalletCardStatus
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>VALID = 0;</code>
     */
    VALID(0),
    /**
     * <code>EXPIRED = 1;</code>
     */
    EXPIRED(1),
    ;

    /**
     * <code>VALID = 0;</code>
     */
    public static final int VALID_VALUE = 0;
    /**
     * <code>EXPIRED = 1;</code>
     */
    public static final int EXPIRED_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static WalletCardStatus valueOf(int value) {
      return forNumber(value);
    }

    public static WalletCardStatus forNumber(int value) {
      switch (value) {
        case 0: return VALID;
        case 1: return EXPIRED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<WalletCardStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        WalletCardStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<WalletCardStatus>() {
            public WalletCardStatus findValueByNumber(int number) {
              return WalletCardStatus.forNumber(number);
            }
          };

    private final int value;

    private WalletCardStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:sync_pb.WalletMaskedCreditCard.WalletCardStatus)
  }

  /**
   * Protobuf enum {@code sync_pb.WalletMaskedCreditCard.WalletCardType}
   */
  public enum WalletCardType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>AMEX = 1;</code>
     */
    AMEX(1),
    /**
     * <code>DISCOVER = 2;</code>
     */
    DISCOVER(2),
    /**
     * <code>JCB = 3;</code>
     */
    JCB(3),
    /**
     * <code>MAESTRO = 4;</code>
     */
    MAESTRO(4),
    /**
     * <code>MASTER_CARD = 5;</code>
     */
    MASTER_CARD(5),
    /**
     * <code>SOLO = 6;</code>
     */
    SOLO(6),
    /**
     * <code>SWITCH = 7;</code>
     */
    SWITCH(7),
    /**
     * <code>VISA = 8;</code>
     */
    VISA(8),
    /**
     * <code>UNIONPAY = 9;</code>
     */
    UNIONPAY(9),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>AMEX = 1;</code>
     */
    public static final int AMEX_VALUE = 1;
    /**
     * <code>DISCOVER = 2;</code>
     */
    public static final int DISCOVER_VALUE = 2;
    /**
     * <code>JCB = 3;</code>
     */
    public static final int JCB_VALUE = 3;
    /**
     * <code>MAESTRO = 4;</code>
     */
    public static final int MAESTRO_VALUE = 4;
    /**
     * <code>MASTER_CARD = 5;</code>
     */
    public static final int MASTER_CARD_VALUE = 5;
    /**
     * <code>SOLO = 6;</code>
     */
    public static final int SOLO_VALUE = 6;
    /**
     * <code>SWITCH = 7;</code>
     */
    public static final int SWITCH_VALUE = 7;
    /**
     * <code>VISA = 8;</code>
     */
    public static final int VISA_VALUE = 8;
    /**
     * <code>UNIONPAY = 9;</code>
     */
    public static final int UNIONPAY_VALUE = 9;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static WalletCardType valueOf(int value) {
      return forNumber(value);
    }

    public static WalletCardType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return AMEX;
        case 2: return DISCOVER;
        case 3: return JCB;
        case 4: return MAESTRO;
        case 5: return MASTER_CARD;
        case 6: return SOLO;
        case 7: return SWITCH;
        case 8: return VISA;
        case 9: return UNIONPAY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<WalletCardType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        WalletCardType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<WalletCardType>() {
            public WalletCardType findValueByNumber(int number) {
              return WalletCardType.forNumber(number);
            }
          };

    private final int value;

    private WalletCardType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:sync_pb.WalletMaskedCreditCard.WalletCardType)
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private java.lang.String id_;
  /**
   * <pre>
   * Server-generated unique ID string. This is opaque to the client.
   * </pre>
   *
   * <code>optional string id = 1;</code>
   */
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <pre>
   * Server-generated unique ID string. This is opaque to the client.
   * </pre>
   *
   * <code>optional string id = 1;</code>
   */
  public java.lang.String getId() {
    return id_;
  }
  /**
   * <pre>
   * Server-generated unique ID string. This is opaque to the client.
   * </pre>
   *
   * <code>optional string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <pre>
   * Server-generated unique ID string. This is opaque to the client.
   * </pre>
   *
   * <code>optional string id = 1;</code>
   */
  private void setId(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    id_ = value;
  }
  /**
   * <pre>
   * Server-generated unique ID string. This is opaque to the client.
   * </pre>
   *
   * <code>optional string id = 1;</code>
   */
  private void clearId() {
    bitField0_ = (bitField0_ & ~0x00000001);
    id_ = getDefaultInstance().getId();
  }
  /**
   * <pre>
   * Server-generated unique ID string. This is opaque to the client.
   * </pre>
   *
   * <code>optional string id = 1;</code>
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
    id_ = value.toStringUtf8();
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private int status_;
  /**
   * <pre>
   * What the server thinks of this card.
   * </pre>
   *
   * <code>optional .sync_pb.WalletMaskedCreditCard.WalletCardStatus status = 2;</code>
   */
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <pre>
   * What the server thinks of this card.
   * </pre>
   *
   * <code>optional .sync_pb.WalletMaskedCreditCard.WalletCardStatus status = 2;</code>
   */
  public org.chromium.components.sync.protocol.WalletMaskedCreditCard.WalletCardStatus getStatus() {
    org.chromium.components.sync.protocol.WalletMaskedCreditCard.WalletCardStatus result = org.chromium.components.sync.protocol.WalletMaskedCreditCard.WalletCardStatus.forNumber(status_);
    return result == null ? org.chromium.components.sync.protocol.WalletMaskedCreditCard.WalletCardStatus.VALID : result;
  }
  /**
   * <pre>
   * What the server thinks of this card.
   * </pre>
   *
   * <code>optional .sync_pb.WalletMaskedCreditCard.WalletCardStatus status = 2;</code>
   */
  private void setStatus(org.chromium.components.sync.protocol.WalletMaskedCreditCard.WalletCardStatus value) {
    if (value == null) {
      throw new NullPointerException();
    }
    bitField0_ |= 0x00000002;
    status_ = value.getNumber();
  }
  /**
   * <pre>
   * What the server thinks of this card.
   * </pre>
   *
   * <code>optional .sync_pb.WalletMaskedCreditCard.WalletCardStatus status = 2;</code>
   */
  private void clearStatus() {
    bitField0_ = (bitField0_ & ~0x00000002);
    status_ = 0;
  }

  public static final int NAME_ON_CARD_FIELD_NUMBER = 3;
  private java.lang.String nameOnCard_;
  /**
   * <code>optional string name_on_card = 3;</code>
   */
  public boolean hasNameOnCard() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string name_on_card = 3;</code>
   */
  public java.lang.String getNameOnCard() {
    return nameOnCard_;
  }
  /**
   * <code>optional string name_on_card = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNameOnCardBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(nameOnCard_);
  }
  /**
   * <code>optional string name_on_card = 3;</code>
   */
  private void setNameOnCard(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
    nameOnCard_ = value;
  }
  /**
   * <code>optional string name_on_card = 3;</code>
   */
  private void clearNameOnCard() {
    bitField0_ = (bitField0_ & ~0x00000004);
    nameOnCard_ = getDefaultInstance().getNameOnCard();
  }
  /**
   * <code>optional string name_on_card = 3;</code>
   */
  private void setNameOnCardBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
    nameOnCard_ = value.toStringUtf8();
  }

  public static final int TYPE_FIELD_NUMBER = 4;
  private int type_;
  /**
   * <code>optional .sync_pb.WalletMaskedCreditCard.WalletCardType type = 4;</code>
   */
  public boolean hasType() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional .sync_pb.WalletMaskedCreditCard.WalletCardType type = 4;</code>
   */
  public org.chromium.components.sync.protocol.WalletMaskedCreditCard.WalletCardType getType() {
    org.chromium.components.sync.protocol.WalletMaskedCreditCard.WalletCardType result = org.chromium.components.sync.protocol.WalletMaskedCreditCard.WalletCardType.forNumber(type_);
    return result == null ? org.chromium.components.sync.protocol.WalletMaskedCreditCard.WalletCardType.UNKNOWN : result;
  }
  /**
   * <code>optional .sync_pb.WalletMaskedCreditCard.WalletCardType type = 4;</code>
   */
  private void setType(org.chromium.components.sync.protocol.WalletMaskedCreditCard.WalletCardType value) {
    if (value == null) {
      throw new NullPointerException();
    }
    bitField0_ |= 0x00000008;
    type_ = value.getNumber();
  }
  /**
   * <code>optional .sync_pb.WalletMaskedCreditCard.WalletCardType type = 4;</code>
   */
  private void clearType() {
    bitField0_ = (bitField0_ & ~0x00000008);
    type_ = 0;
  }

  public static final int LAST_FOUR_FIELD_NUMBER = 5;
  private java.lang.String lastFour_;
  /**
   * <pre>
   * Last 4 digits of the credit card number.
   * </pre>
   *
   * <code>optional string last_four = 5;</code>
   */
  public boolean hasLastFour() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <pre>
   * Last 4 digits of the credit card number.
   * </pre>
   *
   * <code>optional string last_four = 5;</code>
   */
  public java.lang.String getLastFour() {
    return lastFour_;
  }
  /**
   * <pre>
   * Last 4 digits of the credit card number.
   * </pre>
   *
   * <code>optional string last_four = 5;</code>
   */
  public com.google.protobuf.ByteString
      getLastFourBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(lastFour_);
  }
  /**
   * <pre>
   * Last 4 digits of the credit card number.
   * </pre>
   *
   * <code>optional string last_four = 5;</code>
   */
  private void setLastFour(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
    lastFour_ = value;
  }
  /**
   * <pre>
   * Last 4 digits of the credit card number.
   * </pre>
   *
   * <code>optional string last_four = 5;</code>
   */
  private void clearLastFour() {
    bitField0_ = (bitField0_ & ~0x00000010);
    lastFour_ = getDefaultInstance().getLastFour();
  }
  /**
   * <pre>
   * Last 4 digits of the credit card number.
   * </pre>
   *
   * <code>optional string last_four = 5;</code>
   */
  private void setLastFourBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
    lastFour_ = value.toStringUtf8();
  }

  public static final int EXP_MONTH_FIELD_NUMBER = 6;
  private int expMonth_;
  /**
   * <pre>
   * Month number 1-12.
   * </pre>
   *
   * <code>optional int32 exp_month = 6;</code>
   */
  public boolean hasExpMonth() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <pre>
   * Month number 1-12.
   * </pre>
   *
   * <code>optional int32 exp_month = 6;</code>
   */
  public int getExpMonth() {
    return expMonth_;
  }
  /**
   * <pre>
   * Month number 1-12.
   * </pre>
   *
   * <code>optional int32 exp_month = 6;</code>
   */
  private void setExpMonth(int value) {
    bitField0_ |= 0x00000020;
    expMonth_ = value;
  }
  /**
   * <pre>
   * Month number 1-12.
   * </pre>
   *
   * <code>optional int32 exp_month = 6;</code>
   */
  private void clearExpMonth() {
    bitField0_ = (bitField0_ & ~0x00000020);
    expMonth_ = 0;
  }

  public static final int EXP_YEAR_FIELD_NUMBER = 7;
  private int expYear_;
  /**
   * <pre>
   * Four-digit year (e.g. 2017).
   * </pre>
   *
   * <code>optional int32 exp_year = 7;</code>
   */
  public boolean hasExpYear() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <pre>
   * Four-digit year (e.g. 2017).
   * </pre>
   *
   * <code>optional int32 exp_year = 7;</code>
   */
  public int getExpYear() {
    return expYear_;
  }
  /**
   * <pre>
   * Four-digit year (e.g. 2017).
   * </pre>
   *
   * <code>optional int32 exp_year = 7;</code>
   */
  private void setExpYear(int value) {
    bitField0_ |= 0x00000040;
    expYear_ = value;
  }
  /**
   * <pre>
   * Four-digit year (e.g. 2017).
   * </pre>
   *
   * <code>optional int32 exp_year = 7;</code>
   */
  private void clearExpYear() {
    bitField0_ = (bitField0_ & ~0x00000040);
    expYear_ = 0;
  }

  public static final int BILLING_ADDRESS_ID_FIELD_NUMBER = 8;
  private java.lang.String billingAddressId_;
  /**
   * <pre>
   * The WalletPostalAddress.id of the billing address.
   * </pre>
   *
   * <code>optional string billing_address_id = 8;</code>
   */
  public boolean hasBillingAddressId() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <pre>
   * The WalletPostalAddress.id of the billing address.
   * </pre>
   *
   * <code>optional string billing_address_id = 8;</code>
   */
  public java.lang.String getBillingAddressId() {
    return billingAddressId_;
  }
  /**
   * <pre>
   * The WalletPostalAddress.id of the billing address.
   * </pre>
   *
   * <code>optional string billing_address_id = 8;</code>
   */
  public com.google.protobuf.ByteString
      getBillingAddressIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(billingAddressId_);
  }
  /**
   * <pre>
   * The WalletPostalAddress.id of the billing address.
   * </pre>
   *
   * <code>optional string billing_address_id = 8;</code>
   */
  private void setBillingAddressId(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
    billingAddressId_ = value;
  }
  /**
   * <pre>
   * The WalletPostalAddress.id of the billing address.
   * </pre>
   *
   * <code>optional string billing_address_id = 8;</code>
   */
  private void clearBillingAddressId() {
    bitField0_ = (bitField0_ & ~0x00000080);
    billingAddressId_ = getDefaultInstance().getBillingAddressId();
  }
  /**
   * <pre>
   * The WalletPostalAddress.id of the billing address.
   * </pre>
   *
   * <code>optional string billing_address_id = 8;</code>
   */
  private void setBillingAddressIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
    billingAddressId_ = value.toStringUtf8();
  }

  public static final int BANK_NAME_FIELD_NUMBER = 10;
  private java.lang.String bankName_;
  /**
   * <pre>
   * Issuing Bank name which is internationalized (e.g. "Chase", "工商银行")
   * </pre>
   *
   * <code>optional string bank_name = 10;</code>
   */
  public boolean hasBankName() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <pre>
   * Issuing Bank name which is internationalized (e.g. "Chase", "工商银行")
   * </pre>
   *
   * <code>optional string bank_name = 10;</code>
   */
  public java.lang.String getBankName() {
    return bankName_;
  }
  /**
   * <pre>
   * Issuing Bank name which is internationalized (e.g. "Chase", "工商银行")
   * </pre>
   *
   * <code>optional string bank_name = 10;</code>
   */
  public com.google.protobuf.ByteString
      getBankNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(bankName_);
  }
  /**
   * <pre>
   * Issuing Bank name which is internationalized (e.g. "Chase", "工商银行")
   * </pre>
   *
   * <code>optional string bank_name = 10;</code>
   */
  private void setBankName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
    bankName_ = value;
  }
  /**
   * <pre>
   * Issuing Bank name which is internationalized (e.g. "Chase", "工商银行")
   * </pre>
   *
   * <code>optional string bank_name = 10;</code>
   */
  private void clearBankName() {
    bitField0_ = (bitField0_ & ~0x00000100);
    bankName_ = getDefaultInstance().getBankName();
  }
  /**
   * <pre>
   * Issuing Bank name which is internationalized (e.g. "Chase", "工商银行")
   * </pre>
   *
   * <code>optional string bank_name = 10;</code>
   */
  private void setBankNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
    bankName_ = value.toStringUtf8();
  }

  public static final int CLOUD_TOKEN_DATA_FIELD_NUMBER = 11;
  private org.chromium.components.sync.protocol.CloudTokenData cloudTokenData_;
  /**
   * <pre>
   * TODO(crbug.com/1020740): Deprecated, remove this once dependent change is
   * done.
   * Use WalletCreditCardCloudTokenData instead. This field will be set if
   * a cloud token is available for the instrument.
   * </pre>
   *
   * <code>optional .sync_pb.CloudTokenData cloud_token_data = 11;</code>
   */
  public boolean hasCloudTokenData() {
    return ((bitField0_ & 0x00000200) == 0x00000200);
  }
  /**
   * <pre>
   * TODO(crbug.com/1020740): Deprecated, remove this once dependent change is
   * done.
   * Use WalletCreditCardCloudTokenData instead. This field will be set if
   * a cloud token is available for the instrument.
   * </pre>
   *
   * <code>optional .sync_pb.CloudTokenData cloud_token_data = 11;</code>
   */
  public org.chromium.components.sync.protocol.CloudTokenData getCloudTokenData() {
    return cloudTokenData_ == null ? org.chromium.components.sync.protocol.CloudTokenData.getDefaultInstance() : cloudTokenData_;
  }
  /**
   * <pre>
   * TODO(crbug.com/1020740): Deprecated, remove this once dependent change is
   * done.
   * Use WalletCreditCardCloudTokenData instead. This field will be set if
   * a cloud token is available for the instrument.
   * </pre>
   *
   * <code>optional .sync_pb.CloudTokenData cloud_token_data = 11;</code>
   */
  private void setCloudTokenData(org.chromium.components.sync.protocol.CloudTokenData value) {
    if (value == null) {
      throw new NullPointerException();
    }
    cloudTokenData_ = value;
    bitField0_ |= 0x00000200;
    }
  /**
   * <pre>
   * TODO(crbug.com/1020740): Deprecated, remove this once dependent change is
   * done.
   * Use WalletCreditCardCloudTokenData instead. This field will be set if
   * a cloud token is available for the instrument.
   * </pre>
   *
   * <code>optional .sync_pb.CloudTokenData cloud_token_data = 11;</code>
   */
  private void setCloudTokenData(
      org.chromium.components.sync.protocol.CloudTokenData.Builder builderForValue) {
    cloudTokenData_ = builderForValue.build();
    bitField0_ |= 0x00000200;
  }
  /**
   * <pre>
   * TODO(crbug.com/1020740): Deprecated, remove this once dependent change is
   * done.
   * Use WalletCreditCardCloudTokenData instead. This field will be set if
   * a cloud token is available for the instrument.
   * </pre>
   *
   * <code>optional .sync_pb.CloudTokenData cloud_token_data = 11;</code>
   */
  private void mergeCloudTokenData(org.chromium.components.sync.protocol.CloudTokenData value) {
    if (cloudTokenData_ != null &&
        cloudTokenData_ != org.chromium.components.sync.protocol.CloudTokenData.getDefaultInstance()) {
      cloudTokenData_ =
        org.chromium.components.sync.protocol.CloudTokenData.newBuilder(cloudTokenData_).mergeFrom(value).buildPartial();
    } else {
      cloudTokenData_ = value;
    }
    bitField0_ |= 0x00000200;
  }
  /**
   * <pre>
   * TODO(crbug.com/1020740): Deprecated, remove this once dependent change is
   * done.
   * Use WalletCreditCardCloudTokenData instead. This field will be set if
   * a cloud token is available for the instrument.
   * </pre>
   *
   * <code>optional .sync_pb.CloudTokenData cloud_token_data = 11;</code>
   */
  private void clearCloudTokenData() {  cloudTokenData_ = null;
    bitField0_ = (bitField0_ & ~0x00000200);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeString(1, getId());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeEnum(2, status_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeString(3, getNameOnCard());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeEnum(4, type_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeString(5, getLastFour());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeInt32(6, expMonth_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeInt32(7, expYear_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeString(8, getBillingAddressId());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeString(10, getBankName());
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      output.writeMessage(11, getCloudTokenData());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getId());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, status_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(3, getNameOnCard());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, type_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(5, getLastFour());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, expMonth_);
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, expYear_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(8, getBillingAddressId());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(10, getBankName());
    }
    if (((bitField0_ & 0x00000200) == 0x00000200)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getCloudTokenData());
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static org.chromium.components.sync.protocol.WalletMaskedCreditCard parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.WalletMaskedCreditCard parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.WalletMaskedCreditCard parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.chromium.components.sync.protocol.WalletMaskedCreditCard parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.WalletMaskedCreditCard parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.WalletMaskedCreditCard parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.WalletMaskedCreditCard parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.WalletMaskedCreditCard parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.chromium.components.sync.protocol.WalletMaskedCreditCard parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.chromium.components.sync.protocol.WalletMaskedCreditCard parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.chromium.components.sync.protocol.WalletMaskedCreditCard prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code sync_pb.WalletMaskedCreditCard}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.chromium.components.sync.protocol.WalletMaskedCreditCard, Builder> implements
      // @@protoc_insertion_point(builder_implements:sync_pb.WalletMaskedCreditCard)
      org.chromium.components.sync.protocol.WalletMaskedCreditCardOrBuilder {
    // Construct using org.chromium.components.sync.protocol.WalletMaskedCreditCard.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Server-generated unique ID string. This is opaque to the client.
     * </pre>
     *
     * <code>optional string id = 1;</code>
     */
    public boolean hasId() {
      return instance.hasId();
    }
    /**
     * <pre>
     * Server-generated unique ID string. This is opaque to the client.
     * </pre>
     *
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      return instance.getId();
    }
    /**
     * <pre>
     * Server-generated unique ID string. This is opaque to the client.
     * </pre>
     *
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <pre>
     * Server-generated unique ID string. This is opaque to the client.
     * </pre>
     *
     * <code>optional string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <pre>
     * Server-generated unique ID string. This is opaque to the client.
     * </pre>
     *
     * <code>optional string id = 1;</code>
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <pre>
     * Server-generated unique ID string. This is opaque to the client.
     * </pre>
     *
     * <code>optional string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * What the server thinks of this card.
     * </pre>
     *
     * <code>optional .sync_pb.WalletMaskedCreditCard.WalletCardStatus status = 2;</code>
     */
    public boolean hasStatus() {
      return instance.hasStatus();
    }
    /**
     * <pre>
     * What the server thinks of this card.
     * </pre>
     *
     * <code>optional .sync_pb.WalletMaskedCreditCard.WalletCardStatus status = 2;</code>
     */
    public org.chromium.components.sync.protocol.WalletMaskedCreditCard.WalletCardStatus getStatus() {
      return instance.getStatus();
    }
    /**
     * <pre>
     * What the server thinks of this card.
     * </pre>
     *
     * <code>optional .sync_pb.WalletMaskedCreditCard.WalletCardStatus status = 2;</code>
     */
    public Builder setStatus(org.chromium.components.sync.protocol.WalletMaskedCreditCard.WalletCardStatus value) {
      copyOnWrite();
      instance.setStatus(value);
      return this;
    }
    /**
     * <pre>
     * What the server thinks of this card.
     * </pre>
     *
     * <code>optional .sync_pb.WalletMaskedCreditCard.WalletCardStatus status = 2;</code>
     */
    public Builder clearStatus() {
      copyOnWrite();
      instance.clearStatus();
      return this;
    }

    /**
     * <code>optional string name_on_card = 3;</code>
     */
    public boolean hasNameOnCard() {
      return instance.hasNameOnCard();
    }
    /**
     * <code>optional string name_on_card = 3;</code>
     */
    public java.lang.String getNameOnCard() {
      return instance.getNameOnCard();
    }
    /**
     * <code>optional string name_on_card = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameOnCardBytes() {
      return instance.getNameOnCardBytes();
    }
    /**
     * <code>optional string name_on_card = 3;</code>
     */
    public Builder setNameOnCard(
        java.lang.String value) {
      copyOnWrite();
      instance.setNameOnCard(value);
      return this;
    }
    /**
     * <code>optional string name_on_card = 3;</code>
     */
    public Builder clearNameOnCard() {
      copyOnWrite();
      instance.clearNameOnCard();
      return this;
    }
    /**
     * <code>optional string name_on_card = 3;</code>
     */
    public Builder setNameOnCardBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameOnCardBytes(value);
      return this;
    }

    /**
     * <code>optional .sync_pb.WalletMaskedCreditCard.WalletCardType type = 4;</code>
     */
    public boolean hasType() {
      return instance.hasType();
    }
    /**
     * <code>optional .sync_pb.WalletMaskedCreditCard.WalletCardType type = 4;</code>
     */
    public org.chromium.components.sync.protocol.WalletMaskedCreditCard.WalletCardType getType() {
      return instance.getType();
    }
    /**
     * <code>optional .sync_pb.WalletMaskedCreditCard.WalletCardType type = 4;</code>
     */
    public Builder setType(org.chromium.components.sync.protocol.WalletMaskedCreditCard.WalletCardType value) {
      copyOnWrite();
      instance.setType(value);
      return this;
    }
    /**
     * <code>optional .sync_pb.WalletMaskedCreditCard.WalletCardType type = 4;</code>
     */
    public Builder clearType() {
      copyOnWrite();
      instance.clearType();
      return this;
    }

    /**
     * <pre>
     * Last 4 digits of the credit card number.
     * </pre>
     *
     * <code>optional string last_four = 5;</code>
     */
    public boolean hasLastFour() {
      return instance.hasLastFour();
    }
    /**
     * <pre>
     * Last 4 digits of the credit card number.
     * </pre>
     *
     * <code>optional string last_four = 5;</code>
     */
    public java.lang.String getLastFour() {
      return instance.getLastFour();
    }
    /**
     * <pre>
     * Last 4 digits of the credit card number.
     * </pre>
     *
     * <code>optional string last_four = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLastFourBytes() {
      return instance.getLastFourBytes();
    }
    /**
     * <pre>
     * Last 4 digits of the credit card number.
     * </pre>
     *
     * <code>optional string last_four = 5;</code>
     */
    public Builder setLastFour(
        java.lang.String value) {
      copyOnWrite();
      instance.setLastFour(value);
      return this;
    }
    /**
     * <pre>
     * Last 4 digits of the credit card number.
     * </pre>
     *
     * <code>optional string last_four = 5;</code>
     */
    public Builder clearLastFour() {
      copyOnWrite();
      instance.clearLastFour();
      return this;
    }
    /**
     * <pre>
     * Last 4 digits of the credit card number.
     * </pre>
     *
     * <code>optional string last_four = 5;</code>
     */
    public Builder setLastFourBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLastFourBytes(value);
      return this;
    }

    /**
     * <pre>
     * Month number 1-12.
     * </pre>
     *
     * <code>optional int32 exp_month = 6;</code>
     */
    public boolean hasExpMonth() {
      return instance.hasExpMonth();
    }
    /**
     * <pre>
     * Month number 1-12.
     * </pre>
     *
     * <code>optional int32 exp_month = 6;</code>
     */
    public int getExpMonth() {
      return instance.getExpMonth();
    }
    /**
     * <pre>
     * Month number 1-12.
     * </pre>
     *
     * <code>optional int32 exp_month = 6;</code>
     */
    public Builder setExpMonth(int value) {
      copyOnWrite();
      instance.setExpMonth(value);
      return this;
    }
    /**
     * <pre>
     * Month number 1-12.
     * </pre>
     *
     * <code>optional int32 exp_month = 6;</code>
     */
    public Builder clearExpMonth() {
      copyOnWrite();
      instance.clearExpMonth();
      return this;
    }

    /**
     * <pre>
     * Four-digit year (e.g. 2017).
     * </pre>
     *
     * <code>optional int32 exp_year = 7;</code>
     */
    public boolean hasExpYear() {
      return instance.hasExpYear();
    }
    /**
     * <pre>
     * Four-digit year (e.g. 2017).
     * </pre>
     *
     * <code>optional int32 exp_year = 7;</code>
     */
    public int getExpYear() {
      return instance.getExpYear();
    }
    /**
     * <pre>
     * Four-digit year (e.g. 2017).
     * </pre>
     *
     * <code>optional int32 exp_year = 7;</code>
     */
    public Builder setExpYear(int value) {
      copyOnWrite();
      instance.setExpYear(value);
      return this;
    }
    /**
     * <pre>
     * Four-digit year (e.g. 2017).
     * </pre>
     *
     * <code>optional int32 exp_year = 7;</code>
     */
    public Builder clearExpYear() {
      copyOnWrite();
      instance.clearExpYear();
      return this;
    }

    /**
     * <pre>
     * The WalletPostalAddress.id of the billing address.
     * </pre>
     *
     * <code>optional string billing_address_id = 8;</code>
     */
    public boolean hasBillingAddressId() {
      return instance.hasBillingAddressId();
    }
    /**
     * <pre>
     * The WalletPostalAddress.id of the billing address.
     * </pre>
     *
     * <code>optional string billing_address_id = 8;</code>
     */
    public java.lang.String getBillingAddressId() {
      return instance.getBillingAddressId();
    }
    /**
     * <pre>
     * The WalletPostalAddress.id of the billing address.
     * </pre>
     *
     * <code>optional string billing_address_id = 8;</code>
     */
    public com.google.protobuf.ByteString
        getBillingAddressIdBytes() {
      return instance.getBillingAddressIdBytes();
    }
    /**
     * <pre>
     * The WalletPostalAddress.id of the billing address.
     * </pre>
     *
     * <code>optional string billing_address_id = 8;</code>
     */
    public Builder setBillingAddressId(
        java.lang.String value) {
      copyOnWrite();
      instance.setBillingAddressId(value);
      return this;
    }
    /**
     * <pre>
     * The WalletPostalAddress.id of the billing address.
     * </pre>
     *
     * <code>optional string billing_address_id = 8;</code>
     */
    public Builder clearBillingAddressId() {
      copyOnWrite();
      instance.clearBillingAddressId();
      return this;
    }
    /**
     * <pre>
     * The WalletPostalAddress.id of the billing address.
     * </pre>
     *
     * <code>optional string billing_address_id = 8;</code>
     */
    public Builder setBillingAddressIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBillingAddressIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * Issuing Bank name which is internationalized (e.g. "Chase", "工商银行")
     * </pre>
     *
     * <code>optional string bank_name = 10;</code>
     */
    public boolean hasBankName() {
      return instance.hasBankName();
    }
    /**
     * <pre>
     * Issuing Bank name which is internationalized (e.g. "Chase", "工商银行")
     * </pre>
     *
     * <code>optional string bank_name = 10;</code>
     */
    public java.lang.String getBankName() {
      return instance.getBankName();
    }
    /**
     * <pre>
     * Issuing Bank name which is internationalized (e.g. "Chase", "工商银行")
     * </pre>
     *
     * <code>optional string bank_name = 10;</code>
     */
    public com.google.protobuf.ByteString
        getBankNameBytes() {
      return instance.getBankNameBytes();
    }
    /**
     * <pre>
     * Issuing Bank name which is internationalized (e.g. "Chase", "工商银行")
     * </pre>
     *
     * <code>optional string bank_name = 10;</code>
     */
    public Builder setBankName(
        java.lang.String value) {
      copyOnWrite();
      instance.setBankName(value);
      return this;
    }
    /**
     * <pre>
     * Issuing Bank name which is internationalized (e.g. "Chase", "工商银行")
     * </pre>
     *
     * <code>optional string bank_name = 10;</code>
     */
    public Builder clearBankName() {
      copyOnWrite();
      instance.clearBankName();
      return this;
    }
    /**
     * <pre>
     * Issuing Bank name which is internationalized (e.g. "Chase", "工商银行")
     * </pre>
     *
     * <code>optional string bank_name = 10;</code>
     */
    public Builder setBankNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBankNameBytes(value);
      return this;
    }

    /**
     * <pre>
     * TODO(crbug.com/1020740): Deprecated, remove this once dependent change is
     * done.
     * Use WalletCreditCardCloudTokenData instead. This field will be set if
     * a cloud token is available for the instrument.
     * </pre>
     *
     * <code>optional .sync_pb.CloudTokenData cloud_token_data = 11;</code>
     */
    public boolean hasCloudTokenData() {
      return instance.hasCloudTokenData();
    }
    /**
     * <pre>
     * TODO(crbug.com/1020740): Deprecated, remove this once dependent change is
     * done.
     * Use WalletCreditCardCloudTokenData instead. This field will be set if
     * a cloud token is available for the instrument.
     * </pre>
     *
     * <code>optional .sync_pb.CloudTokenData cloud_token_data = 11;</code>
     */
    public org.chromium.components.sync.protocol.CloudTokenData getCloudTokenData() {
      return instance.getCloudTokenData();
    }
    /**
     * <pre>
     * TODO(crbug.com/1020740): Deprecated, remove this once dependent change is
     * done.
     * Use WalletCreditCardCloudTokenData instead. This field will be set if
     * a cloud token is available for the instrument.
     * </pre>
     *
     * <code>optional .sync_pb.CloudTokenData cloud_token_data = 11;</code>
     */
    public Builder setCloudTokenData(org.chromium.components.sync.protocol.CloudTokenData value) {
      copyOnWrite();
      instance.setCloudTokenData(value);
      return this;
      }
    /**
     * <pre>
     * TODO(crbug.com/1020740): Deprecated, remove this once dependent change is
     * done.
     * Use WalletCreditCardCloudTokenData instead. This field will be set if
     * a cloud token is available for the instrument.
     * </pre>
     *
     * <code>optional .sync_pb.CloudTokenData cloud_token_data = 11;</code>
     */
    public Builder setCloudTokenData(
        org.chromium.components.sync.protocol.CloudTokenData.Builder builderForValue) {
      copyOnWrite();
      instance.setCloudTokenData(builderForValue);
      return this;
    }
    /**
     * <pre>
     * TODO(crbug.com/1020740): Deprecated, remove this once dependent change is
     * done.
     * Use WalletCreditCardCloudTokenData instead. This field will be set if
     * a cloud token is available for the instrument.
     * </pre>
     *
     * <code>optional .sync_pb.CloudTokenData cloud_token_data = 11;</code>
     */
    public Builder mergeCloudTokenData(org.chromium.components.sync.protocol.CloudTokenData value) {
      copyOnWrite();
      instance.mergeCloudTokenData(value);
      return this;
    }
    /**
     * <pre>
     * TODO(crbug.com/1020740): Deprecated, remove this once dependent change is
     * done.
     * Use WalletCreditCardCloudTokenData instead. This field will be set if
     * a cloud token is available for the instrument.
     * </pre>
     *
     * <code>optional .sync_pb.CloudTokenData cloud_token_data = 11;</code>
     */
    public Builder clearCloudTokenData() {  copyOnWrite();
      instance.clearCloudTokenData();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:sync_pb.WalletMaskedCreditCard)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.chromium.components.sync.protocol.WalletMaskedCreditCard();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        org.chromium.components.sync.protocol.WalletMaskedCreditCard other = (org.chromium.components.sync.protocol.WalletMaskedCreditCard) arg1;
        id_ = visitor.visitString(
            hasId(), id_,
            other.hasId(), other.id_);
        status_ = visitor.visitInt(hasStatus(), status_,
            other.hasStatus(), other.status_);
        nameOnCard_ = visitor.visitString(
            hasNameOnCard(), nameOnCard_,
            other.hasNameOnCard(), other.nameOnCard_);
        type_ = visitor.visitInt(hasType(), type_,
            other.hasType(), other.type_);
        lastFour_ = visitor.visitString(
            hasLastFour(), lastFour_,
            other.hasLastFour(), other.lastFour_);
        expMonth_ = visitor.visitInt(
            hasExpMonth(), expMonth_,
            other.hasExpMonth(), other.expMonth_);
        expYear_ = visitor.visitInt(
            hasExpYear(), expYear_,
            other.hasExpYear(), other.expYear_);
        billingAddressId_ = visitor.visitString(
            hasBillingAddressId(), billingAddressId_,
            other.hasBillingAddressId(), other.billingAddressId_);
        bankName_ = visitor.visitString(
            hasBankName(), bankName_,
            other.hasBankName(), other.bankName_);
        cloudTokenData_ = visitor.visitMessage(cloudTokenData_, other.cloudTokenData_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readString();
                bitField0_ |= 0x00000001;
                id_ = s;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                org.chromium.components.sync.protocol.WalletMaskedCreditCard.WalletCardStatus value = org.chromium.components.sync.protocol.WalletMaskedCreditCard.WalletCardStatus.forNumber(rawValue);
                if (value == null) {
                  super.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  status_ = rawValue;
                }
                break;
              }
              case 26: {
                String s = input.readString();
                bitField0_ |= 0x00000004;
                nameOnCard_ = s;
                break;
              }
              case 32: {
                int rawValue = input.readEnum();
                org.chromium.components.sync.protocol.WalletMaskedCreditCard.WalletCardType value = org.chromium.components.sync.protocol.WalletMaskedCreditCard.WalletCardType.forNumber(rawValue);
                if (value == null) {
                  super.mergeVarintField(4, rawValue);
                } else {
                  bitField0_ |= 0x00000008;
                  type_ = rawValue;
                }
                break;
              }
              case 42: {
                String s = input.readString();
                bitField0_ |= 0x00000010;
                lastFour_ = s;
                break;
              }
              case 48: {
                bitField0_ |= 0x00000020;
                expMonth_ = input.readInt32();
                break;
              }
              case 56: {
                bitField0_ |= 0x00000040;
                expYear_ = input.readInt32();
                break;
              }
              case 66: {
                String s = input.readString();
                bitField0_ |= 0x00000080;
                billingAddressId_ = s;
                break;
              }
              case 82: {
                String s = input.readString();
                bitField0_ |= 0x00000100;
                bankName_ = s;
                break;
              }
              case 90: {
                org.chromium.components.sync.protocol.CloudTokenData.Builder subBuilder = null;
                if (((bitField0_ & 0x00000200) == 0x00000200)) {
                  subBuilder = cloudTokenData_.toBuilder();
                }
                cloudTokenData_ = input.readMessage(org.chromium.components.sync.protocol.CloudTokenData.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(cloudTokenData_);
                  cloudTokenData_ = subBuilder.buildPartial();
                }
                bitField0_ |= 0x00000200;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (org.chromium.components.sync.protocol.WalletMaskedCreditCard.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:sync_pb.WalletMaskedCreditCard)
  private static final org.chromium.components.sync.protocol.WalletMaskedCreditCard DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new WalletMaskedCreditCard();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static org.chromium.components.sync.protocol.WalletMaskedCreditCard getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<WalletMaskedCreditCard> PARSER;

  public static com.google.protobuf.Parser<WalletMaskedCreditCard> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

