// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: autofill_specifics.proto

package org.chromium.components.sync.protocol;

public interface WalletMaskedCreditCardOrBuilder extends
    // @@protoc_insertion_point(interface_extends:sync_pb.WalletMaskedCreditCard)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Server-generated unique ID string. This is opaque to the client.
   * </pre>
   *
   * <code>optional string id = 1;</code>
   */
  boolean hasId();
  /**
   * <pre>
   * Server-generated unique ID string. This is opaque to the client.
   * </pre>
   *
   * <code>optional string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   * Server-generated unique ID string. This is opaque to the client.
   * </pre>
   *
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * What the server thinks of this card.
   * </pre>
   *
   * <code>optional .sync_pb.WalletMaskedCreditCard.WalletCardStatus status = 2;</code>
   */
  boolean hasStatus();
  /**
   * <pre>
   * What the server thinks of this card.
   * </pre>
   *
   * <code>optional .sync_pb.WalletMaskedCreditCard.WalletCardStatus status = 2;</code>
   */
  org.chromium.components.sync.protocol.WalletMaskedCreditCard.WalletCardStatus getStatus();

  /**
   * <code>optional string name_on_card = 3;</code>
   */
  boolean hasNameOnCard();
  /**
   * <code>optional string name_on_card = 3;</code>
   */
  java.lang.String getNameOnCard();
  /**
   * <code>optional string name_on_card = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameOnCardBytes();

  /**
   * <code>optional .sync_pb.WalletMaskedCreditCard.WalletCardType type = 4;</code>
   */
  boolean hasType();
  /**
   * <code>optional .sync_pb.WalletMaskedCreditCard.WalletCardType type = 4;</code>
   */
  org.chromium.components.sync.protocol.WalletMaskedCreditCard.WalletCardType getType();

  /**
   * <pre>
   * Last 4 digits of the credit card number.
   * </pre>
   *
   * <code>optional string last_four = 5;</code>
   */
  boolean hasLastFour();
  /**
   * <pre>
   * Last 4 digits of the credit card number.
   * </pre>
   *
   * <code>optional string last_four = 5;</code>
   */
  java.lang.String getLastFour();
  /**
   * <pre>
   * Last 4 digits of the credit card number.
   * </pre>
   *
   * <code>optional string last_four = 5;</code>
   */
  com.google.protobuf.ByteString
      getLastFourBytes();

  /**
   * <pre>
   * Month number 1-12.
   * </pre>
   *
   * <code>optional int32 exp_month = 6;</code>
   */
  boolean hasExpMonth();
  /**
   * <pre>
   * Month number 1-12.
   * </pre>
   *
   * <code>optional int32 exp_month = 6;</code>
   */
  int getExpMonth();

  /**
   * <pre>
   * Four-digit year (e.g. 2017).
   * </pre>
   *
   * <code>optional int32 exp_year = 7;</code>
   */
  boolean hasExpYear();
  /**
   * <pre>
   * Four-digit year (e.g. 2017).
   * </pre>
   *
   * <code>optional int32 exp_year = 7;</code>
   */
  int getExpYear();

  /**
   * <pre>
   * The WalletPostalAddress.id of the billing address.
   * </pre>
   *
   * <code>optional string billing_address_id = 8;</code>
   */
  boolean hasBillingAddressId();
  /**
   * <pre>
   * The WalletPostalAddress.id of the billing address.
   * </pre>
   *
   * <code>optional string billing_address_id = 8;</code>
   */
  java.lang.String getBillingAddressId();
  /**
   * <pre>
   * The WalletPostalAddress.id of the billing address.
   * </pre>
   *
   * <code>optional string billing_address_id = 8;</code>
   */
  com.google.protobuf.ByteString
      getBillingAddressIdBytes();

  /**
   * <pre>
   * Issuing Bank name which is internationalized (e.g. "Chase", "工商银行")
   * </pre>
   *
   * <code>optional string bank_name = 10;</code>
   */
  boolean hasBankName();
  /**
   * <pre>
   * Issuing Bank name which is internationalized (e.g. "Chase", "工商银行")
   * </pre>
   *
   * <code>optional string bank_name = 10;</code>
   */
  java.lang.String getBankName();
  /**
   * <pre>
   * Issuing Bank name which is internationalized (e.g. "Chase", "工商银行")
   * </pre>
   *
   * <code>optional string bank_name = 10;</code>
   */
  com.google.protobuf.ByteString
      getBankNameBytes();

  /**
   * <pre>
   * TODO(crbug.com/1020740): Deprecated, remove this once dependent change is
   * done.
   * Use WalletCreditCardCloudTokenData instead. This field will be set if
   * a cloud token is available for the instrument.
   * </pre>
   *
   * <code>optional .sync_pb.CloudTokenData cloud_token_data = 11;</code>
   */
  boolean hasCloudTokenData();
  /**
   * <pre>
   * TODO(crbug.com/1020740): Deprecated, remove this once dependent change is
   * done.
   * Use WalletCreditCardCloudTokenData instead. This field will be set if
   * a cloud token is available for the instrument.
   * </pre>
   *
   * <code>optional .sync_pb.CloudTokenData cloud_token_data = 11;</code>
   */
  org.chromium.components.sync.protocol.CloudTokenData getCloudTokenData();
}
